import {
  DirectorySubmission,
  DuplicateDetection,
  BlogContact,
  OutreachTemplate,
  AutomationTask,
  SeoTask,
  AiGenerationSummary,
} from '@/types';

// Top 100 Most Impactful SEO Directory Sites (plus social coverage)
export const mockDirectorySubmissions: DirectorySubmission[] = [
  // Tier 1: Essential (DA 90+)
  {
    id: '1',
    directoryName: 'Google My Business',
    url: 'https://business.google.com',
    domainAuthority: 100,
    status: 'pending',
    submissionDate: new Date('2024-01-15'),
    nextResubmission: new Date('2024-02-01'),
    tier: 'Essential',
    focusArea: 'Local',
    automation: 'auto',
    notes: 'Auto-sync NAP monthly; monitor for review responses. Review link https://g.page/r/CUB8bZ_ibMbwEBI/review.',
    aiDescription:
      'Elevate local visibility with a complete Google My Business profile featuring verified NAP data, service categories, and fresh media.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-25T10:12:00Z'),
    anthropicModel: 'claude-3-opus',
  },
  {
    id: '2',
    directoryName: 'Yelp',
    url: 'https://yelp.com',
    domainAuthority: 94,
    status: 'pending',
    submissionDate: new Date('2024-01-15'),
    nextResubmission: new Date('2024-02-03'),
    tier: 'Essential',
    focusArea: 'Local',
    automation: 'auto',
    notes: 'Push latest photos via automation workflow. Settings portal https://biz.yelp.com/settings.',
    aiDescription:
      'Stand out on Yelp with an optimized description that highlights customer wins, rapid response times, and top-tier support ratings.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-25T10:14:00Z'),
    anthropicModel: 'claude-3-opus',
  },
  {
    id: '3',
    directoryName: 'Crunchbase',
    url: 'https://crunchbase.com',
    domainAuthority: 92,
    status: 'pending',
    submissionDate: new Date('2024-01-20'),
    nextResubmission: new Date('2024-02-12'),
    tier: 'Essential',
    focusArea: 'Startup',
    automation: 'auto',
    notes: 'Auto-publish funding updates from Supabase feed. Profile live at https://www.crunchbase.com/organization/purrify.',
    aiDescription:
      'Profile the company as a fast-scaling automation platform delivering AI-assisted SEO outreach with measurable pipeline impact.',
    aiStatus: 'regenerating',
    lastAiGeneration: new Date('2024-01-26T09:32:00Z'),
    anthropicModel: 'claude-3-sonnet',
  },
  {
    id: '4',
    directoryName: 'Product Hunt',
    url: 'https://producthunt.com',
    domainAuthority: 92,
    status: 'pending',
    submissionDate: new Date('2024-01-15'),
    nextResubmission: new Date('2024-03-01'),
    tier: 'High Impact',
    focusArea: 'Product',
    automation: 'manual',
    notes: 'Teaser saved; hold for launch day, not yet launched.',
    aiDescription:
      'Spotlight the product-led SEO copilot with automated submissions, AI duplicate prevention, and outreach playbooks for founders.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-24T21:04:00Z'),
    anthropicModel: 'claude-3-opus',
  },
  {
    id: '5',
    directoryName: 'Hacker News',
    url: 'https://news.ycombinator.com',
    domainAuthority: 94,
    status: 'pending',
    submissionDate: new Date('2024-01-22'),
    nextResubmission: new Date('2024-02-15'),
    tier: 'High Impact',
    focusArea: 'Community',
    automation: 'manual',
    notes: 'Manual repost with fresh angle; watch AI duplicate suppression.',
    aiDescription:
      'Frame the launch as an engineering-first toolkit that automates top-tier directory placement without repetitive copy.',
    aiStatus: 'draft',
    lastAiGeneration: new Date('2024-01-23T18:45:00Z'),
    anthropicModel: 'claude-3-sonnet',
  },
  {
    id: '6',
    directoryName: 'Facebook Business',
    url: 'https://facebook.com/business',
    domainAuthority: 96,
    status: 'pending',
    submissionDate: new Date('2024-01-10'),
    nextResubmission: new Date('2024-02-08'),
    tier: 'Essential',
    focusArea: 'Local',
    automation: 'auto',
    notes: 'Automated via Meta API connector.',
    aiDescription:
      'Deliver a concise overview that emphasizes community engagement, real-time messaging, and location-accurate details.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-25T10:16:00Z'),
    anthropicModel: 'claude-3-haiku',
  },
  {
    id: '7',
    directoryName: 'LinkedIn Company',
    url: 'https://linkedin.com',
    domainAuthority: 98,
    status: 'pending',
    submissionDate: new Date('2024-01-12'),
    nextResubmission: new Date('2024-02-09'),
    tier: 'Essential',
    focusArea: 'Startup',
    automation: 'auto',
    notes: 'Auto-sync employee count and tagline monthly.',
    aiDescription:
      'Position the team as growth-minded operators scaling AI-driven SEO automation for GTM leaders worldwide.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-25T11:05:00Z'),
    anthropicModel: 'claude-3-opus',
  },
  // Essential social channels marked complete
  {
    id: '101',
    directoryName: 'X (Twitter)',
    url: 'https://x.com/PurrifyHQ',
    domainAuthority: 94,
    status: 'pending',
    submissionDate: new Date('2024-01-26'),
    nextResubmission: new Date('2024-02-20'),
    tier: 'Essential',
    focusArea: 'Community',
    automation: 'manual',
    notes: 'Live handle; monitor mentions daily and pin launch thread.',
    aiDescription:
      'Keep the feed active with ship logs, customer love, and fast replies to inbound questions.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-26T16:40:00Z'),
    anthropicModel: 'claude-3-sonnet',
  },
  {
    id: '102',
    directoryName: 'Instagram',
    url: 'https://www.instagram.com/purrifyhq/',
    domainAuthority: 96,
    status: 'pending',
    submissionDate: new Date('2024-01-26'),
    nextResubmission: new Date('2024-02-22'),
    tier: 'Essential',
    focusArea: 'Community',
    automation: 'manual',
    notes: 'Profile live with hero assets; schedule weekly reels.',
    aiDescription:
      'Highlight behind-the-scenes product walkthroughs and customer pets to stay on brand.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-26T16:45:00Z'),
    anthropicModel: 'claude-3-haiku',
  },
  {
    id: '103',
    directoryName: 'TikTok',
    url: 'https://www.tiktok.com/@purrifyhq',
    domainAuthority: 92,
    status: 'pending',
    submissionDate: new Date('2024-01-26'),
    nextResubmission: new Date('2024-02-24'),
    tier: 'High Impact',
    focusArea: 'Community',
    automation: 'manual',
    notes: 'Short-form intro published; monitor comments.',
    aiDescription:
      'Publish playful micro-demos and customer stories to tap into discovery traffic.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-26T16:50:00Z'),
    anthropicModel: 'claude-3-haiku',
  },
  {
    id: '104',
    directoryName: 'YouTube Channel',
    url: 'https://www.youtube.com/@PurrifyHQ',
    domainAuthority: 100,
    status: 'pending',
    submissionDate: new Date('2024-01-26'),
    nextResubmission: new Date('2024-02-28'),
    tier: 'Essential',
    focusArea: 'Community',
    automation: 'manual',
    notes: 'Channel art live; upload cadence every other week.',
    aiDescription:
      'Anchor long-form demos and testimonials to nurture high-intent evaluators.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-26T16:55:00Z'),
    anthropicModel: 'claude-3-opus',
  },
  {
    id: '8',
    directoryName: 'Apple Maps',
    url: 'https://mapsconnect.apple.com',
    domainAuthority: 100,
    status: 'pending',
    submissionDate: new Date('2024-01-18'),
    nextResubmission: new Date('2024-02-11'),
    tier: 'Essential',
    focusArea: 'Local',
    automation: 'auto',
    notes: 'Monthly sync to maintain pin accuracy.',
    aiDescription:
      'Guide iOS searchers to accurate contact info, storefront details, and up-to-date appointment links.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-25T10:18:00Z'),
    anthropicModel: 'claude-3-haiku',
  },
  {
    id: '9',
    directoryName: 'Bing Places',
    url: 'https://bingplaces.com',
    domainAuthority: 93,
    status: 'pending',
    submissionDate: new Date('2024-01-14'),
    nextResubmission: new Date('2024-02-07'),
    tier: 'Essential',
    focusArea: 'Local',
    automation: 'auto',
    notes: 'Synced alongside GMB push; verified via https://www.bing.com/forbusiness/singleEntity?bizid=dc537d86-4d9b-47d2-9c8f-5019712edd9f.',
    aiDescription:
      'Mirror the high-intent messaging from GMB while reinforcing Microsoft ecosystem coverage.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-25T10:20:00Z'),
    anthropicModel: 'claude-3-haiku',
  },
  {
    id: '10',
    directoryName: 'Better Business Bureau',
    url: 'https://bbb.org',
    domainAuthority: 91,
    status: 'pending',
    submissionDate: new Date('2024-01-16'),
    nextResubmission: new Date('2024-02-19'),
    tier: 'High Impact',
    focusArea: 'Review',
    automation: 'manual',
    notes: 'Manual monthly rating review with compliance team.',
    aiDescription:
      'Reassure prospects with proof of compliance, verified reviews, and transparent dispute handling.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-24T19:12:00Z'),
    anthropicModel: 'claude-3-opus',
  },

  // Tier 2: High Impact (DA 80-89)
  { id: '11', directoryName: 'Indie Hackers', url: 'https://indiehackers.com', domainAuthority: 88, status: 'pending', submissionDate: new Date('2024-01-20') },
  { id: '12', directoryName: 'AlternativeTo', url: 'https://alternativeto.net', domainAuthority: 87, status: 'pending', submissionDate: new Date('2024-01-18') },
  { id: '13', directoryName: 'G2', url: 'https://g2.com', domainAuthority: 89, status: 'pending', submissionDate: new Date('2024-01-21') },
  { id: '14', directoryName: 'Capterra', url: 'https://capterra.com', domainAuthority: 88, status: 'pending', submissionDate: new Date('2024-01-17') },
  { id: '15', directoryName: 'TrustRadius', url: 'https://trustradius.com', domainAuthority: 84, status: 'pending', submissionDate: new Date('2024-01-23') },
  { id: '16', directoryName: 'GetApp', url: 'https://getapp.com', domainAuthority: 83, status: 'pending', submissionDate: new Date('2024-01-19') },
  { id: '17', directoryName: 'Software Advice', url: 'https://softwareadvice.com', domainAuthority: 85, status: 'pending', submissionDate: new Date('2024-01-22') },
  {
    id: '18',
    directoryName: 'Trustpilot',
    url: 'https://trustpilot.com',
    domainAuthority: 89,
    status: 'pending',
    submissionDate: new Date('2024-01-15'),
    notes: 'Live review page https://www.trustpilot.com/review/purrify.ca.',
  },
  { id: '19', directoryName: 'Foursquare', url: 'https://foursquare.com', domainAuthority: 86, status: 'pending', submissionDate: new Date('2024-01-16') },
  { id: '20', directoryName: 'Yellow Pages', url: 'https://yellowpages.com', domainAuthority: 82, status: 'pending', submissionDate: new Date('2024-01-14') },

  // Tier 3: Strong Impact (DA 70-79)
  { id: '21', directoryName: 'BetaList', url: 'https://betalist.com', domainAuthority: 79, status: 'pending', submissionDate: new Date('2024-01-22'), nextResubmission: new Date('2024-02-05') },
  { id: '22', directoryName: 'SaaSHub', url: 'https://saashub.com', domainAuthority: 76, status: 'pending', submissionDate: new Date('2024-01-21') },
  { id: '23', directoryName: 'Slashdot', url: 'https://slashdot.org', domainAuthority: 78, status: 'pending', submissionDate: new Date('2024-01-18') },
  { id: '24', directoryName: 'AngelList', url: 'https://angel.co', domainAuthority: 79, status: 'pending', submissionDate: new Date('2024-01-17') },
  { id: '25', directoryName: 'StartupRanking', url: 'https://startupranking.com', domainAuthority: 72, status: 'pending', submissionDate: new Date('2024-01-20') },
  { id: '26', directoryName: 'Launching Next', url: 'https://launchingnext.com', domainAuthority: 71, status: 'pending', submissionDate: new Date('2024-01-23') },
  { id: '27', directoryName: 'Startup Buffer', url: 'https://startupbuffer.com', domainAuthority: 70, status: 'pending', submissionDate: new Date('2024-01-19') },
  { id: '28', directoryName: 'Killer Startups', url: 'https://killerstartups.com', domainAuthority: 73, status: 'pending', submissionDate: new Date('2024-01-21') },
  { id: '29', directoryName: 'StartupLift', url: 'https://startuplift.com', domainAuthority: 74, status: 'pending', submissionDate: new Date('2024-01-18') },
  { id: '30', directoryName: 'Startup88', url: 'https://startup88.com', domainAuthority: 71, status: 'pending', submissionDate: new Date('2024-01-22') },

  // Tier 4: Good Impact (DA 60-69)
  { id: '31', directoryName: 'Betapage', url: 'https://betapage.co', domainAuthority: 68, status: 'pending', submissionDate: new Date('2024-01-17') },
  { id: '32', directoryName: 'Startup Stash', url: 'https://startupstash.com', domainAuthority: 67, status: 'pending', submissionDate: new Date('2024-01-20') },
  { id: '33', directoryName: 'Startup Inspire', url: 'https://startupinspire.com', domainAuthority: 65, status: 'pending', submissionDate: new Date('2024-01-19') },
  { id: '34', directoryName: 'All Startups', url: 'https://allstartups.info', domainAuthority: 64, status: 'pending', submissionDate: new Date('2024-01-23') },
  { id: '35', directoryName: 'Startup Base', url: 'https://startupbase.io', domainAuthority: 66, status: 'pending', submissionDate: new Date('2024-01-21') },
  { id: '36', directoryName: 'Feedmyapp', url: 'https://feedmyapp.com', domainAuthority: 63, status: 'pending', submissionDate: new Date('2024-01-18') },
  { id: '37', directoryName: 'Startupbeat', url: 'https://startupbeat.com', domainAuthority: 62, status: 'pending', submissionDate: new Date('2024-01-22') },
  { id: '38', directoryName: 'Erlibird', url: 'https://erlibird.com', domainAuthority: 61, status: 'pending', submissionDate: new Date('2024-01-20') },
  { id: '39', directoryName: 'Springwise', url: 'https://springwise.com', domainAuthority: 69, status: 'pending', submissionDate: new Date('2024-01-17') },
  { id: '40', directoryName: 'Startup Collections', url: 'https://startupcollections.com', domainAuthority: 60, status: 'pending', submissionDate: new Date('2024-01-19') },

  // Tier 5: Solid Impact (DA 50-59)
  { id: '41', directoryName: 'Startups.co', url: 'https://startups.co', domainAuthority: 59, status: 'pending', submissionDate: new Date('2024-01-21') },
  { id: '42', directoryName: 'Startup Tracker', url: 'https://startuptracker.io', domainAuthority: 58, status: 'pending', submissionDate: new Date('2024-01-18') },
  { id: '43', directoryName: 'Geekwire', url: 'https://geekwire.com', domainAuthority: 57, status: 'pending', submissionDate: new Date('2024-01-23') },
  { id: '44', directoryName: 'Launched', url: 'https://launched.io', domainAuthority: 56, status: 'pending', submissionDate: new Date('2024-01-20') },
  { id: '45', directoryName: 'Startup Blink', url: 'https://startupblink.com', domainAuthority: 55, status: 'pending', submissionDate: new Date('2024-01-19') },
  { id: '46', directoryName: 'Startup Dope', url: 'https://startupdope.com', domainAuthority: 54, status: 'pending', submissionDate: new Date('2024-01-22') },
  { id: '47', directoryName: 'Startup Register', url: 'https://startupregister.io', domainAuthority: 53, status: 'pending', submissionDate: new Date('2024-01-21') },
  { id: '48', directoryName: 'Venture Beat', url: 'https://venturebeat.com', domainAuthority: 59, status: 'pending', submissionDate: new Date('2024-01-17') },
  { id: '49', directoryName: 'Tech Pluto', url: 'https://techpluto.com', domainAuthority: 52, status: 'pending', submissionDate: new Date('2024-01-18') },
  { id: '50', directoryName: 'Startup Resources', url: 'https://startupresources.io', domainAuthority: 51, status: 'pending', submissionDate: new Date('2024-01-23') },

  // Additional High-Value Directories (DA 45-70)
  { id: '51', directoryName: 'Reddit (r/startups)', url: 'https://reddit.com/r/startups', domainAuthority: 91, status: 'pending', submissionDate: new Date('2024-01-16') },
  { id: '52', directoryName: 'Stack Overflow', url: 'https://stackoverflow.com', domainAuthority: 95, status: 'pending', submissionDate: new Date('2024-01-15') },
  { id: '53', directoryName: 'GitHub', url: 'https://github.com', domainAuthority: 96, status: 'pending', submissionDate: new Date('2024-01-14') },
  { id: '54', directoryName: 'Dev.to', url: 'https://dev.to', domainAuthority: 82, status: 'pending', submissionDate: new Date('2024-01-21') },
  { id: '55', directoryName: 'Hashnode', url: 'https://hashnode.com', domainAuthority: 75, status: 'pending', submissionDate: new Date('2024-01-19') },
  { id: '56', directoryName: 'Medium', url: 'https://medium.com', domainAuthority: 96, status: 'pending', submissionDate: new Date('2024-01-15') },
  { id: '57', directoryName: 'Quora', url: 'https://quora.com', domainAuthority: 93, status: 'pending', submissionDate: new Date('2024-01-16') },
  { id: '58', directoryName: 'Slideshare', url: 'https://slideshare.net', domainAuthority: 88, status: 'pending', submissionDate: new Date('2024-01-20') },
  { id: '59', directoryName: 'Behance', url: 'https://behance.net', domainAuthority: 92, status: 'pending', submissionDate: new Date('2024-01-17') },
  { id: '60', directoryName: 'Dribbble', url: 'https://dribbble.com', domainAuthority: 90, status: 'pending', submissionDate: new Date('2024-01-18') },
  { id: '105', directoryName: 'Substack', url: 'https://purrifyhq.substack.com', domainAuthority: 88, status: 'pending', submissionDate: new Date('2024-01-27') },
  { id: '106', directoryName: 'Amazon Storefront', url: 'https://www.amazon.com/stores/purrify', domainAuthority: 96, status: 'pending', submissionDate: new Date('2024-01-27') },

  // Industry-Specific High DA (DA 50-85)
  { id: '61', directoryName: 'TechCrunch', url: 'https://techcrunch.com', domainAuthority: 93, status: 'pending', submissionDate: new Date('2024-01-23') },
  { id: '62', directoryName: 'The Next Web', url: 'https://thenextweb.com', domainAuthority: 85, status: 'pending', submissionDate: new Date('2024-01-21') },
  { id: '63', directoryName: 'Mashable', url: 'https://mashable.com', domainAuthority: 92, status: 'pending', submissionDate: new Date('2024-01-17') },
  { id: '64', directoryName: 'Wired', url: 'https://wired.com', domainAuthority: 93, status: 'pending', submissionDate: new Date('2024-01-16') },
  { id: '65', directoryName: 'Fast Company', url: 'https://fastcompany.com', domainAuthority: 91, status: 'pending', submissionDate: new Date('2024-01-20') },
  { id: '66', directoryName: 'Inc.com', url: 'https://inc.com', domainAuthority: 92, status: 'pending', submissionDate: new Date('2024-01-18') },
  { id: '67', directoryName: 'Entrepreneur', url: 'https://entrepreneur.com', domainAuthority: 90, status: 'pending', submissionDate: new Date('2024-01-19') },
  { id: '68', directoryName: 'Forbes', url: 'https://forbes.com', domainAuthority: 95, status: 'pending', submissionDate: new Date('2024-01-22') },
  { id: '69', directoryName: 'Business Insider', url: 'https://businessinsider.com', domainAuthority: 93, status: 'pending', submissionDate: new Date('2024-01-21') },
  { id: '70', directoryName: 'The Verge', url: 'https://theverge.com', domainAuthority: 91, status: 'pending', submissionDate: new Date('2024-01-17') },

  // SaaS & Tech Directories (DA 45-75)
  { id: '71', directoryName: 'SaaS Genius', url: 'https://saasgenius.com', domainAuthority: 68, status: 'pending', submissionDate: new Date('2024-01-19') },
  { id: '72', directoryName: 'SaaS Worthy', url: 'https://saasworthy.com', domainAuthority: 65, status: 'pending', submissionDate: new Date('2024-01-20') },
  { id: '73', directoryName: 'Siftery', url: 'https://siftery.com', domainAuthority: 62, status: 'pending', submissionDate: new Date('2024-01-18') },
  { id: '74', directoryName: 'StackShare', url: 'https://stackshare.io', domainAuthority: 75, status: 'pending', submissionDate: new Date('2024-01-17') },
  { id: '75', directoryName: 'Crozdesk', url: 'https://crozdesk.com', domainAuthority: 61, status: 'pending', submissionDate: new Date('2024-01-23') },
  { id: '76', directoryName: 'FinancesOnline', url: 'https://financesonline.com', domainAuthority: 70, status: 'pending', submissionDate: new Date('2024-01-21') },
  { id: '77', directoryName: 'Featured Customers', url: 'https://featuredcustomers.com', domainAuthority: 64, status: 'pending', submissionDate: new Date('2024-01-19') },
  { id: '78', directoryName: 'Serchen', url: 'https://serchen.com', domainAuthority: 58, status: 'pending', submissionDate: new Date('2024-01-18') },
  { id: '79', directoryName: 'Sourceforge', url: 'https://sourceforge.net', domainAuthority: 87, status: 'pending', submissionDate: new Date('2024-01-16') },
  { id: '80', directoryName: 'Softpedia', url: 'https://softpedia.com', domainAuthority: 81, status: 'pending', submissionDate: new Date('2024-01-20') },

  // Startup & Business Directories (DA 40-65)
  { id: '81', directoryName: 'F6S', url: 'https://f6s.com', domainAuthority: 72, status: 'pending', submissionDate: new Date('2024-01-17') },
  { id: '82', directoryName: 'Gust', url: 'https://gust.com', domainAuthority: 68, status: 'pending', submissionDate: new Date('2024-01-22') },
  { id: '83', directoryName: 'Owler', url: 'https://owler.com', domainAuthority: 65, status: 'pending', submissionDate: new Date('2024-01-21') },
  { id: '84', directoryName: 'Manta', url: 'https://manta.com', domainAuthority: 70, status: 'pending', submissionDate: new Date('2024-01-19') },
  { id: '85', directoryName: 'Clutch', url: 'https://clutch.co', domainAuthority: 78, status: 'pending', submissionDate: new Date('2024-01-18') },
  { id: '86', directoryName: 'GoodFirms', url: 'https://goodfirms.co', domainAuthority: 63, status: 'pending', submissionDate: new Date('2024-01-20') },
  { id: '87', directoryName: 'The Manifest', url: 'https://themanifest.com', domainAuthority: 69, status: 'pending', submissionDate: new Date('2024-01-17') },
  { id: '88', directoryName: 'Visual Objects', url: 'https://visualobjects.com', domainAuthority: 61, status: 'pending', submissionDate: new Date('2024-01-23') },
  { id: '89', directoryName: 'Sitejabber', url: 'https://sitejabber.com', domainAuthority: 74, status: 'pending', submissionDate: new Date('2024-01-21') },
  { id: '90', directoryName: 'Glassdoor', url: 'https://glassdoor.com', domainAuthority: 89, status: 'pending', submissionDate: new Date('2024-01-16') },

  // Final 10 High-Value Directories
  { id: '91', directoryName: 'Pitchbook', url: 'https://pitchbook.com', domainAuthority: 80, status: 'pending', submissionDate: new Date('2024-01-18') },
  { id: '92', directoryName: 'CB Insights', url: 'https://cbinsights.com', domainAuthority: 77, status: 'pending', submissionDate: new Date('2024-01-20') },
  { id: '93', directoryName: 'Craft.co', url: 'https://craft.co', domainAuthority: 71, status: 'pending', submissionDate: new Date('2024-01-19') },
  { id: '94', directoryName: 'Tracxn', url: 'https://tracxn.com', domainAuthority: 69, status: 'pending', submissionDate: new Date('2024-01-22') },
  { id: '95', directoryName: 'Dealroom', url: 'https://dealroom.co', domainAuthority: 67, status: 'pending', submissionDate: new Date('2024-01-21') },
  { id: '96', directoryName: 'Wellfound (AngelList)', url: 'https://wellfound.com', domainAuthority: 79, status: 'pending', submissionDate: new Date('2024-01-17') },
  { id: '97', directoryName: 'Startup Grind', url: 'https://startupgrind.com', domainAuthority: 73, status: 'pending', submissionDate: new Date('2024-01-18') },
  { id: '98', directoryName: 'Betabound', url: 'https://betabound.com', domainAuthority: 64, status: 'pending', submissionDate: new Date('2024-01-23') },
  { id: '99', directoryName: 'Startup Savant', url: 'https://startupsavant.com', domainAuthority: 66, status: 'pending', submissionDate: new Date('2024-01-20') },
  { id: '100', directoryName: 'Startup Nation', url: 'https://startupnation.com', domainAuthority: 68, status: 'pending', submissionDate: new Date('2024-01-19') },

  // Cat owner outreach network (status: pets)
  {
    id: '107',
    directoryName: 'Catster',
    url: 'https://www.catster.com',
    domainAuthority: 82,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Feature Purrify in Catster lifestyle stories for reach among cat adopters.',
  },
  {
    id: '108',
    directoryName: 'The Cat Site',
    url: 'https://thecatsite.com',
    domainAuthority: 77,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Partner on forum AMAs about SEO for boutique pet brands.',
  },
  {
    id: '109',
    directoryName: 'Modern Cat Magazine',
    url: 'https://moderncat.com',
    domainAuthority: 74,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Pitch guest article on building local search visibility for cat cafes.',
  },
  {
    id: '110',
    directoryName: 'Adventure Cats',
    url: 'https://www.adventurecats.org',
    domainAuthority: 64,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Highlight travel-friendly brand listings for outdoor cat guardians.',
  },
  {
    id: '111',
    directoryName: 'Purrington Post',
    url: 'https://www.purringtonpost.com',
    domainAuthority: 61,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Submit founder Q&A on automating directory updates for pet retailers.',
  },
  {
    id: '112',
    directoryName: 'Meowingtons Blog',
    url: 'https://www.meowingtons.com/blogs/news',
    domainAuthority: 67,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Secure sponsored content on DTC launch playbooks for cat brands.',
  },
  {
    id: '113',
    directoryName: 'Love Meow',
    url: 'https://www.lovemeow.com',
    domainAuthority: 79,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Share case study on boosting rescue visibility with directory coverage.',
  },
  {
    id: '114',
    directoryName: 'iHeartCats',
    url: 'https://iheartcats.com',
    domainAuthority: 70,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Create co-branded guide on fundraising funnels for shelters.',
  },
  {
    id: '115',
    directoryName: 'The Conscious Cat',
    url: 'https://consciouscat.net',
    domainAuthority: 63,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Offer expert column on ethical SEO for holistic pet care.',
  },
  {
    id: '116',
    directoryName: 'Cat Friendly Homes',
    url: 'https://catfriendly.com',
    domainAuthority: 68,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Promote compliance checklist for veterinary directory listings.',
  },
  {
    id: '117',
    directoryName: 'Feline Living',
    url: 'https://www.felineliving.net',
    domainAuthority: 62,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Guest tutorial on mapping keywords to cat care buyer journeys.',
  },
  {
    id: '118',
    directoryName: 'CatWorld',
    url: 'https://www.catworld.com.au',
    domainAuthority: 58,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Localize listing recommendations for ANZ cat services.',
  },
  {
    id: '119',
    directoryName: 'Cat Lovers Only',
    url: 'https://www.catloversonly.com',
    domainAuthority: 56,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Spotlight checklist for indie cat shop directory hygiene.',
  },
  {
    id: '120',
    directoryName: 'CatTime',
    url: 'https://cattime.com',
    domainAuthority: 74,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Publish trends report on search demand for cat wellness products.',
  },
  {
    id: '121',
    directoryName: 'Petfinder Cats',
    url: 'https://www.petfinder.com/cats',
    domainAuthority: 88,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Align adoption partners with accurate location data feeds.',
  },
  {
    id: '122',
    directoryName: 'Chewy Cat Central',
    url: 'https://be.chewy.com/cat',
    domainAuthority: 84,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Co-author sponsored lesson on product-led directory launches.',
  },
  {
    id: '123',
    directoryName: 'Petco Cat Care',
    url: 'https://www.petco.com/cat-care',
    domainAuthority: 86,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Share syndication plan for multi-location cat grooming brands.',
  },
  {
    id: '124',
    directoryName: 'PetSmart Cat Resource',
    url: 'https://www.petsmart.com/learn/cat',
    domainAuthority: 83,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Secure educational listing for in-store cat adoption events.',
  },
  {
    id: '125',
    directoryName: 'Tuft + Paw Journal',
    url: 'https://www.tuftandpaw.com/blogs/journal',
    domainAuthority: 60,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Pitch content on design-led SEO for modern cat furniture brands.',
  },
  {
    id: '126',
    directoryName: 'Modkat Blog',
    url: 'https://blog.modkat.com',
    domainAuthority: 57,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Offer data story on litter box buyers via directory analytics.',
  },
  {
    id: '127',
    directoryName: 'Hauspanther',
    url: 'https://www.hauspanther.com',
    domainAuthority: 66,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Feature portfolio of automated listings for boutique cat brands.',
  },
  {
    id: '128',
    directoryName: 'Litter-Robot Blog',
    url: 'https://www.litter-robot.com/blog',
    domainAuthority: 73,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Publish automation case study for smart litter tech companies.',
  },
  {
    id: '129',
    directoryName: 'KittyClysm',
    url: 'https://kittyclysm.com',
    domainAuthority: 54,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Education piece on keyword research for cat bloggers.',
  },
  {
    id: '130',
    directoryName: 'Cat Behavior Associates',
    url: 'https://www.catbehaviorassociates.com/blog',
    domainAuthority: 59,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Outline structured data tips for behavior consultants.',
  },
  {
    id: '131',
    directoryName: 'Cat Wisdom 101',
    url: 'https://catwisdom101.com',
    domainAuthority: 55,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Amplify wellness-focused listings for senior cat care.',
  },
  {
    id: '132',
    directoryName: 'Pawsome Kitty',
    url: 'https://www.pawsomekitty.com',
    domainAuthority: 52,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Guest article on micro-influencer outreach for cat boutiques.',
  },
  {
    id: '133',
    directoryName: 'The Catnip Times',
    url: 'https://www.thecatniptimes.com',
    domainAuthority: 65,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Plan editorial takeover timed with National Cat Day.',
  },
  {
    id: '134',
    directoryName: 'Jackson Galaxy Blog',
    url: 'https://www.jacksongalaxy.com/blogs/blog',
    domainAuthority: 72,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Align behavioral SEO tips with celebrity endorsement.',
  },
  {
    id: '135',
    directoryName: 'Best Friends Cat Program',
    url: 'https://resources.bestfriends.org/cats',
    domainAuthority: 83,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Support national rescue partners with directory templates.',
  },
  {
    id: '136',
    directoryName: 'Alley Cat Allies Blog',
    url: 'https://www.alleycat.org/resources',
    domainAuthority: 80,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Provide advocacy toolkit with local listing guidance.',
  },
  {
    id: '137',
    directoryName: 'Cats Protection Advice',
    url: 'https://www.cats.org.uk/help-and-advice',
    domainAuthority: 88,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Build UK-specific directory map for charity partners.',
  },
  {
    id: '138',
    directoryName: 'ASPCA Cat Care',
    url: 'https://www.aspca.org/pet-care/cat-care',
    domainAuthority: 92,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Align educational resources with automated listing feeds.',
  },
  {
    id: '139',
    directoryName: 'Humane Society Cat Resources',
    url: 'https://www.humanesociety.org/resources/cats',
    domainAuthority: 89,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Provide templated outreach for municipal shelter directories.',
  },
  {
    id: '140',
    directoryName: 'PetMD Cats Library',
    url: 'https://www.petmd.com/cat',
    domainAuthority: 91,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Develop medical SEO checklist for veterinary partners.',
  },
  {
    id: '141',
    directoryName: 'Rover Cats Guide',
    url: 'https://www.rover.com/blog/cats',
    domainAuthority: 88,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Publish marketplace success story leveraging Purrify submissions.',
  },
  {
    id: '142',
    directoryName: 'Wag! Cats Hub',
    url: 'https://wagwalking.com/cat',
    domainAuthority: 75,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Launch joint webinar on SEO for mobile cat services.',
  },
  {
    id: '143',
    directoryName: 'Daily Paws Cats',
    url: 'https://www.dailypaws.com/cats-kittens',
    domainAuthority: 79,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Secure editorial featuring launch of Purrify listings toolkit.',
  },
  {
    id: '144',
    directoryName: 'Martha Stewart Cats',
    url: 'https://www.marthastewart.com/cats',
    domainAuthority: 90,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Contribute home design SEO tips for stylish cat owners.',
  },
  {
    id: '145',
    directoryName: 'Apartment Therapy Cats',
    url: 'https://www.apartmenttherapy.com/collection/pets/cats',
    domainAuthority: 88,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Pitch space-saving directory strategies for urban cat startups.',
  },
  {
    id: '146',
    directoryName: 'Bustle Cats & Pets',
    url: 'https://www.bustle.com/pets/cats',
    domainAuthority: 92,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Coordinate PR feature on AI-powered pet marketing.',
  },
  {
    id: '147',
    directoryName: 'Country Living Cats',
    url: 'https://www.countryliving.com/pets/cats',
    domainAuthority: 87,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Showcase rural success stories using automated listings.',
  },
  {
    id: '148',
    directoryName: 'Catit Community',
    url: 'https://www.catit.com/community',
    domainAuthority: 62,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Collaborate on product education for cat enrichment brands.',
  },
  {
    id: '149',
    directoryName: 'Cole and Marmalade',
    url: 'https://coleandmarmalade.com',
    domainAuthority: 69,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Secure influencer spotlight on polished directory presence.',
  },
  {
    id: '150',
    directoryName: 'We Love Cats and Kittens',
    url: 'https://welovecatsandkittens.com',
    domainAuthority: 71,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Plan newsletter feature on free cat marketing channels.',
  },
  {
    id: '151',
    directoryName: 'KitNipBox Blog',
    url: 'https://www.kitnipbox.com/blogs/kitnip-blog',
    domainAuthority: 57,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Partner on subscription growth checklist for cat boxes.',
  },
  {
    id: '152',
    directoryName: 'Cat Cafe Directory',
    url: 'https://catcafe.directory',
    domainAuthority: 49,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Aggregate global cat cafe listings managed by Purrify.',
  },
  {
    id: '153',
    directoryName: 'Cat Lady Academy',
    url: 'https://catladyacademy.com/blog',
    domainAuthority: 42,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Offer training module on SEO fundamentals for catpreneurs.',
  },
  {
    id: '154',
    directoryName: 'Purrfect Post Blog',
    url: 'https://www.purrfectpost.com/blog',
    domainAuthority: 53,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Educational content on keyword strategy for product pages.',
  },
  {
    id: '155',
    directoryName: 'Meowtel Blog',
    url: 'https://www.meowtel.com/blog',
    domainAuthority: 58,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Profile sitter marketplace success with automation.',
  },
  {
    id: '156',
    directoryName: 'City the Kitty',
    url: 'https://citythekitty.org/blog',
    domainAuthority: 50,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Support advocacy campaigns with optimized resource listings.',
  },
];

export const mockAutomationTasks: AutomationTask[] = [
  {
    id: 'auto-1',
    name: 'Essential listings refresh',
    cadence: 'monthly',
    nextRun: new Date('2024-02-01'),
    owner: 'Automation Engine',
    status: 'scheduled',
    impact: 'critical',
    relatedDirectories: ['Google My Business', 'Yelp', 'Bing Places'],
    notes: 'Sync NAP, photos, service area across top local profiles.',
  },
  {
    id: 'auto-2',
    name: 'Startup ecosystem sync',
    cadence: 'monthly',
    nextRun: new Date('2024-02-05'),
    owner: 'Automation Engine',
    status: 'scheduled',
    impact: 'high',
    relatedDirectories: ['Crunchbase', 'Product Hunt', 'AngelList'],
    notes: 'Push funding, traction, and product updates automatically.',
  },
  {
    id: 'auto-3',
    name: 'Review generation workflow',
    cadence: 'monthly',
    nextRun: new Date('2024-02-07'),
    owner: 'Success Team',
    status: 'in-progress',
    impact: 'high',
    relatedDirectories: ['Better Business Bureau', 'Trustpilot', 'G2'],
    notes: 'Trigger customer outreach to gather fresh testimonials.',
  },
  {
    id: 'auto-4',
    name: 'Industry niche expansion',
    cadence: 'quarterly',
    nextRun: new Date('2024-03-10'),
    owner: 'Automation Engine',
    status: 'scheduled',
    impact: 'medium',
    relatedDirectories: ['Indie Hackers', 'AlternativeTo', 'SaaSHub'],
    notes: 'Roll new product narrative to community-driven directories.',
  },
];

export const mockSeoTasks: SeoTask[] = [
  {
    id: 'task-1',
    label: 'Submit refreshed listing assets to Yelp and Bing',
    category: 'Listing',
    impactScore: 92,
    status: 'active',
    owner: 'Automation Engine',
    dueDate: new Date('2024-02-03'),
  },
  {
    id: 'task-2',
    label: 'Launch AI-personalized blog outreach sequence',
    category: 'Content',
    impactScore: 88,
    status: 'queued',
    owner: 'Content Ops',
    dueDate: new Date('2024-02-06'),
  },
  {
    id: 'task-3',
    label: 'Secure 15 new G2 and Trustpilot reviews',
    category: 'Review',
    impactScore: 84,
    status: 'active',
    owner: 'Success Team',
    dueDate: new Date('2024-02-12'),
  },
  {
    id: 'task-4',
    label: 'Optimize Crunchbase profile with latest metrics',
    category: 'Listing',
    impactScore: 80,
    status: 'queued',
    owner: 'Growth Squad',
    dueDate: new Date('2024-02-09'),
  },
  {
    id: 'task-5',
    label: 'Publish thought leadership guest post on Startup Insights',
    category: 'Content',
    impactScore: 78,
    status: 'queued',
    owner: 'Content Ops',
    dueDate: new Date('2024-02-15'),
  },
];

// Mock data for duplicate detections
export const mockDuplicateDetections: DuplicateDetection[] = [
  {
    id: '1',
    directoryName: 'StartupBase',
    url: 'https://startupbase.io',
    confidenceScore: 0.95,
    detectedDate: new Date('2024-01-23'),
    status: 'pending',
  },
  {
    id: '2',
    directoryName: 'SaaSHub',
    url: 'https://saashub.com',
    confidenceScore: 0.78,
    detectedDate: new Date('2024-01-24'),
    status: 'pending',
  },
  {
    id: '3',
    directoryName: 'Capterra',
    url: 'https://capterra.com',
    confidenceScore: 0.62,
    detectedDate: new Date('2024-01-25'),
    status: 'accepted',
  },
];

// Mock data for blog contacts
export const mockBlogContacts: BlogContact[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah@techblog.com',
    blogUrl: 'https://techblog.com',
    domainAuthority: 78,
    status: 'responded',
    lastContactDate: new Date('2024-01-20'),
    notes: 'Interested in guest post collaboration',
  },
  {
    id: '2',
    name: 'Mike Chen',
    email: 'mike@startupinsights.io',
    blogUrl: 'https://startupinsights.io',
    domainAuthority: 82,
    status: 'contacted',
    lastContactDate: new Date('2024-01-22'),
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily@devnews.com',
    blogUrl: 'https://devnews.com',
    domainAuthority: 85,
    status: 'new',
  },
  {
    id: '4',
    name: 'David Park',
    email: 'david@saasnews.net',
    blogUrl: 'https://saasnews.net',
    domainAuthority: 76,
    status: 'declined',
    lastContactDate: new Date('2024-01-15'),
    notes: 'Not accepting guest posts currently',
  },
];

// Mock data for outreach templates
export const mockOutreachTemplates: OutreachTemplate[] = [
  {
    id: '1',
    name: 'Initial Outreach',
    subject: 'Guest Post Opportunity for {{blog_name}}',
    body: 'Hi {{contact_name}},\n\nI hope this email finds you well. I\'ve been following {{blog_name}} and really appreciate your content on {{topic}}.\n\nI\'d love to contribute a guest post...',
    category: 'Guest Post',
  },
  {
    id: '2',
    name: 'Follow-up',
    subject: 'Following up on guest post opportunity',
    body: 'Hi {{contact_name}},\n\nI wanted to follow up on my previous email about contributing to {{blog_name}}...',
    category: 'Follow-up',
  },
  {
    id: '3',
    name: 'Product Feature Request',
    subject: 'Feature opportunity: {{product_name}}',
    body: 'Hi {{contact_name}},\n\nI noticed you recently covered {{related_topic}} on {{blog_name}}. I thought you might be interested in {{product_name}}...',
    category: 'Product Feature',
  },
];

export const mockAiSummary: AiGenerationSummary = {
  totalDirectories: mockDirectorySubmissions.length,
  uniqueDescriptions: mockDirectorySubmissions.filter((submission) => submission.aiStatus === 'generated').length,
  averageTokens: 365,
  lastRun: new Date('2024-01-26T10:30:00Z'),
  model: 'claude-3-opus',
};
