import {
  DirectorySubmission,
  DuplicateDetection,
  BlogContact,
  OutreachTemplate,
  AutomationTask,
  SeoTask,
  AiGenerationSummary,
} from '@/types';

// Priority directory and community placements for Purrify
export const mockDirectorySubmissions: DirectorySubmission[] = [
  // Essential Local (DA 90+)
  {
    id: '1',
    directoryName: 'Google Business Profile',
    url: 'https://business.google.com',
    domainAuthority: 100,
    status: 'approved',
    submissionDate: new Date('2024-01-15'),
    nextResubmission: new Date('2024-02-01'),
    tier: 'Essential',
    focusArea: 'Local',
    automation: 'auto',
    notes: 'Auto-sync NAP monthly',
  },
  {
    id: '2',
    directoryName: 'Yelp',
    url: 'https://yelp.com',
    domainAuthority: 94,
    status: 'approved',
    submissionDate: new Date('2024-01-15'),
    tier: 'Essential',
    focusArea: 'Local',
  },
  {
    id: '8',
    directoryName: 'Apple Maps',
    url: 'https://mapsconnect.apple.com',
    domainAuthority: 100,
    status: 'approved',
    submissionDate: new Date('2024-01-18'),
    tier: 'Essential',
    focusArea: 'Local',
  },
  {
    id: '9',
    directoryName: 'Bing Places',
    url: 'https://bingplaces.com',
    domainAuthority: 93,
    status: 'approved',
    submissionDate: new Date('2024-01-14'),
    tier: 'Essential',
    focusArea: 'Local',
  },
  
  // Social Media (DA 90+)
  {
    id: '7',
    directoryName: 'LinkedIn Company',
    url: 'https://linkedin.com',
    domainAuthority: 98,
    status: 'approved',
    submissionDate: new Date('2024-01-12'),
    tier: 'Essential',
    focusArea: 'Community',
  },
  {
    id: '101',
    directoryName: 'X (Twitter)',
    url: 'https://x.com/PurrifyHQ',
    domainAuthority: 94,
    status: 'approved',
    submissionDate: new Date('2024-01-26'),
    tier: 'Essential',
    focusArea: 'Community',
  },
  {
    id: '102',
    directoryName: 'Instagram',
    url: 'https://www.instagram.com/purrifyhq/',
    domainAuthority: 96,
    status: 'approved',
    submissionDate: new Date('2024-01-26'),
    tier: 'Essential',
    focusArea: 'Community',
  },
  {
    id: '103',
    directoryName: 'TikTok',
    url: 'https://www.tiktok.com/@purrifyhq',
    domainAuthority: 92,
    status: 'approved',
    submissionDate: new Date('2024-01-26'),
    tier: 'High Impact',
    focusArea: 'Community',
  },
  {
    id: '104',
    directoryName: 'YouTube Channel',
    url: 'https://www.youtube.com/@PurrifyHQ',
    domainAuthority: 100,
    status: 'approved',
    submissionDate: new Date('2024-01-26'),
    tier: 'Essential',
    focusArea: 'Community',
  },
  {
    id: '6',
    directoryName: 'Facebook Page',
    url: 'https://www.facebook.com/purrifyhq',
    domainAuthority: 96,
    status: 'pending',
    submissionDate: new Date('2024-01-28'),
    tier: 'Essential',
    focusArea: 'Community',
  },
  
  // Reviews
  {
    id: '3',
    directoryName: 'Trustpilot',
    url: 'https://www.trustpilot.com/review/purrify.ca',
    domainAuthority: 89,
    status: 'approved',
    submissionDate: new Date('2024-01-15'),
    tier: 'High Impact',
    focusArea: 'Review',
  },
  
  // Pet & Cat Directories
  {
    id: '10',
    directoryName: 'Catster',
    url: 'https://www.catster.com',
    domainAuthority: 82,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
  },
  {
    id: '11',
    directoryName: 'Love Meow',
    url: 'https://www.lovemeow.com',
    domainAuthority: 79,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
  },
  {
    id: '12',
    directoryName: 'iHeartCats',
    url: 'https://iheartcats.com',
    domainAuthority: 70,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
  },
  {
    id: '13',
    directoryName: 'Petfinder',
    url: 'https://www.petfinder.com',
    domainAuthority: 88,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
  },
  {
    id: '14',
    directoryName: 'PetMD',
    url: 'https://www.petmd.com',
    domainAuthority: 91,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
  },
  {
    id: '15',
    directoryName: 'Daily Paws',
    url: 'https://www.dailypaws.com',
    domainAuthority: 79,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
  },
  {
    id: '16',
    directoryName: 'The Spruce Pets',
    url: 'https://www.thesprucepets.com',
    domainAuthority: 85,
    status: 'pending',
    submissionDate: new Date('2024-01-28'),
    focusArea: 'Pets',
  },
  {
    id: '17',
    directoryName: 'Chewy',
    url: 'https://www.chewy.com',
    domainAuthority: 87,
    status: 'pending',
    submissionDate: new Date('2024-01-28'),
    focusArea: 'Pets',
  },
  {
    id: '18',
    directoryName: 'Petco',
    url: 'https://www.petco.com',
    domainAuthority: 84,
    status: 'pending',
    submissionDate: new Date('2024-01-28'),
    focusArea: 'Pets',
  },
  {
    id: '19',
    directoryName: 'PetSmart',
    url: 'https://www.petsmart.com',
    domainAuthority: 83,
    status: 'pending',
    submissionDate: new Date('2024-01-28'),
    focusArea: 'Pets',
  },
  
  // Product Hunt & Startup Directories
  {
    id: '20',
    directoryName: 'Product Hunt',
    url: 'https://www.producthunt.com',
    domainAuthority: 92,
    status: 'pending',
    submissionDate: new Date('2024-01-29'),
    focusArea: 'Product',
  },
  {
    id: '21',
    directoryName: 'BetaList',
    url: 'https://betalist.com',
    domainAuthority: 78,
    status: 'pending',
    submissionDate: new Date('2024-01-29'),
    focusArea: 'Startup',
  },
  {
    id: '22',
    directoryName: 'Crunchbase',
    url: 'https://www.crunchbase.com',
    domainAuthority: 94,
    status: 'pending',
    submissionDate: new Date('2024-01-29'),
    focusArea: 'Startup',
  },
  {
    id: '23',
    directoryName: 'AngelList',
    url: 'https://angel.co',
    domainAuthority: 91,
    status: 'pending',
    submissionDate: new Date('2024-01-29'),
    focusArea: 'Startup',
  },
  {
    id: '24',
    directoryName: 'F6S',
    url: 'https://www.f6s.com',
    domainAuthority: 76,
    status: 'pending',
    submissionDate: new Date('2024-01-29'),
    focusArea: 'Startup',
  },
  {
    id: '25',
    directoryName: 'Startup Stash',
    url: 'https://startupstash.com',
    domainAuthority: 72,
    status: 'pending',
    submissionDate: new Date('2024-01-29'),
    focusArea: 'Startup',
  },
  {
    id: '26',
    directoryName: 'Launching Next',
    url: 'https://www.launchingnext.com',
    domainAuthority: 68,
    status: 'pending',
    submissionDate: new Date('2024-01-29'),
    focusArea: 'Startup',
  },
  {
    id: '27',
    directoryName: 'Startup Buffer',
    url: 'https://startupbuffer.com',
    domainAuthority: 65,
    status: 'pending',
    submissionDate: new Date('2024-01-29'),
    focusArea: 'Startup',
  },
  {
    id: '28',
    directoryName: 'Killer Startups',
    url: 'https://killerstartups.com',
    domainAuthority: 70,
    status: 'pending',
    submissionDate: new Date('2024-01-29'),
    focusArea: 'Startup',
  },
  {
    id: '29',
    directoryName: 'Startup Ranking',
    url: 'https://www.startupranking.com',
    domainAuthority: 74,
    status: 'pending',
    submissionDate: new Date('2024-01-29'),
    focusArea: 'Startup',
  },
  {
    id: '30',
    directoryName: 'Betapage',
    url: 'https://betapage.co',
    domainAuthority: 69,
    status: 'pending',
    submissionDate: new Date('2024-01-29'),
    focusArea: 'Startup',
  },
  
  // SaaS & Software Directories
  {
    id: '31',
    directoryName: 'G2',
    url: 'https://www.g2.com',
    domainAuthority: 93,
    status: 'pending',
    submissionDate: new Date('2024-01-30'),
    focusArea: 'Review',
  },
  {
    id: '32',
    directoryName: 'Capterra',
    url: 'https://www.capterra.com',
    domainAuthority: 92,
    status: 'pending',
    submissionDate: new Date('2024-01-30'),
    focusArea: 'Review',
  },
  {
    id: '33',
    directoryName: 'Software Advice',
    url: 'https://www.softwareadvice.com',
    domainAuthority: 88,
    status: 'pending',
    submissionDate: new Date('2024-01-30'),
    focusArea: 'Review',
  },
  {
    id: '34',
    directoryName: 'GetApp',
    url: 'https://www.getapp.com',
    domainAuthority: 86,
    status: 'pending',
    submissionDate: new Date('2024-01-30'),
    focusArea: 'Product',
  },
  {
    id: '35',
    directoryName: 'SaaSHub',
    url: 'https://www.saashub.com',
    domainAuthority: 75,
    status: 'pending',
    submissionDate: new Date('2024-01-30'),
    focusArea: 'Product',
  },
  {
    id: '36',
    directoryName: 'AlternativeTo',
    url: 'https://alternativeto.net',
    domainAuthority: 82,
    status: 'pending',
    submissionDate: new Date('2024-01-30'),
    focusArea: 'Product',
  },
  {
    id: '37',
    directoryName: 'Slant',
    url: 'https://www.slant.co',
    domainAuthority: 77,
    status: 'pending',
    submissionDate: new Date('2024-01-30'),
    focusArea: 'Product',
  },
  {
    id: '38',
    directoryName: 'StackShare',
    url: 'https://stackshare.io',
    domainAuthority: 84,
    status: 'pending',
    submissionDate: new Date('2024-01-30'),
    focusArea: 'Product',
  },
  {
    id: '39',
    directoryName: 'Siftery',
    url: 'https://siftery.com',
    domainAuthority: 71,
    status: 'pending',
    submissionDate: new Date('2024-01-30'),
    focusArea: 'Product',
  },
  {
    id: '40',
    directoryName: 'Crozdesk',
    url: 'https://crozdesk.com',
    domainAuthority: 73,
    status: 'pending',
    submissionDate: new Date('2024-01-30'),
    focusArea: 'Product',
  },
  
  // Community & Forums
  {
    id: '41',
    directoryName: 'Reddit r/cats',
    url: 'https://www.reddit.com/r/cats',
    domainAuthority: 99,
    status: 'pending',
    submissionDate: new Date('2024-01-31'),
    focusArea: 'Community',
  },
  {
    id: '42',
    directoryName: 'Reddit r/CatAdvice',
    url: 'https://www.reddit.com/r/CatAdvice',
    domainAuthority: 99,
    status: 'pending',
    submissionDate: new Date('2024-01-31'),
    focusArea: 'Community',
  },
  {
    id: '43',
    directoryName: 'Hacker News',
    url: 'https://news.ycombinator.com',
    domainAuthority: 93,
    status: 'pending',
    submissionDate: new Date('2024-01-31'),
    focusArea: 'Community',
  },
  {
    id: '44',
    directoryName: 'Indie Hackers',
    url: 'https://www.indiehackers.com',
    domainAuthority: 85,
    status: 'pending',
    submissionDate: new Date('2024-01-31'),
    focusArea: 'Community',
  },
  {
    id: '45',
    directoryName: 'Quora',
    url: 'https://www.quora.com',
    domainAuthority: 94,
    status: 'pending',
    submissionDate: new Date('2024-01-31'),
    focusArea: 'Community',
  },
  {
    id: '46',
    directoryName: 'Medium',
    url: 'https://medium.com/@purrify',
    domainAuthority: 96,
    status: 'pending',
    submissionDate: new Date('2024-01-31'),
    focusArea: 'Community',
  },
  {
    id: '47',
    directoryName: 'Dev.to',
    url: 'https://dev.to',
    domainAuthority: 87,
    status: 'pending',
    submissionDate: new Date('2024-01-31'),
    focusArea: 'Community',
  },
  {
    id: '48',
    directoryName: 'Hashnode',
    url: 'https://hashnode.com',
    domainAuthority: 81,
    status: 'pending',
    submissionDate: new Date('2024-01-31'),
    focusArea: 'Community',
  },
  {
    id: '49',
    directoryName: 'Substack',
    url: 'https://substack.com',
    domainAuthority: 92,
    status: 'pending',
    submissionDate: new Date('2024-01-31'),
    focusArea: 'Community',
  },
  {
    id: '50',
    directoryName: 'Discord Communities',
    url: 'https://discord.com',
    domainAuthority: 95,
    status: 'pending',
    submissionDate: new Date('2024-01-31'),
    focusArea: 'Community',
  },
  
  // Business Directories
  {
    id: '51',
    directoryName: 'Yellow Pages',
    url: 'https://www.yellowpages.com',
    domainAuthority: 89,
    status: 'pending',
    submissionDate: new Date('2024-02-01'),
    focusArea: 'Local',
  },
  {
    id: '52',
    directoryName: 'Manta',
    url: 'https://www.manta.com',
    domainAuthority: 82,
    status: 'pending',
    submissionDate: new Date('2024-02-01'),
    focusArea: 'Local',
  },
  {
    id: '53',
    directoryName: 'Foursquare',
    url: 'https://foursquare.com',
    domainAuthority: 93,
    status: 'pending',
    submissionDate: new Date('2024-02-01'),
    focusArea: 'Local',
  },
  {
    id: '54',
    directoryName: 'Hotfrog',
    url: 'https://www.hotfrog.com',
    domainAuthority: 76,
    status: 'pending',
    submissionDate: new Date('2024-02-01'),
    focusArea: 'Local',
  },
  {
    id: '55',
    directoryName: 'Brownbook',
    url: 'https://www.brownbook.net',
    domainAuthority: 74,
    status: 'pending',
    submissionDate: new Date('2024-02-01'),
    focusArea: 'Local',
  },
  {
    id: '56',
    directoryName: 'Cylex',
    url: 'https://www.cylex.ca',
    domainAuthority: 72,
    status: 'pending',
    submissionDate: new Date('2024-02-01'),
    focusArea: 'Local',
  },
  {
    id: '57',
    directoryName: 'Tupalo',
    url: 'https://tupalo.com',
    domainAuthority: 68,
    status: 'pending',
    submissionDate: new Date('2024-02-01'),
    focusArea: 'Local',
  },
  {
    id: '58',
    directoryName: 'Spoke',
    url: 'https://www.spoke.com',
    domainAuthority: 70,
    status: 'pending',
    submissionDate: new Date('2024-02-01'),
    focusArea: 'Local',
  },
  {
    id: '59',
    directoryName: 'Citysquares',
    url: 'https://citysquares.com',
    domainAuthority: 69,
    status: 'pending',
    submissionDate: new Date('2024-02-01'),
    focusArea: 'Local',
  },
  {
    id: '60',
    directoryName: 'Ezlocal',
    url: 'https://ezlocal.com',
    domainAuthority: 67,
    status: 'pending',
    submissionDate: new Date('2024-02-01'),
    focusArea: 'Local',
  },
  
  // Niche Pet & Home Directories
  {
    id: '61',
    directoryName: 'The Cat Site',
    url: 'https://thecatsite.com',
    domainAuthority: 75,
    status: 'pending',
    submissionDate: new Date('2024-02-02'),
    focusArea: 'Pets',
  },
  {
    id: '62',
    directoryName: 'Cat Forum',
    url: 'https://www.catforum.com',
    domainAuthority: 68,
    status: 'pending',
    submissionDate: new Date('2024-02-02'),
    focusArea: 'Pets',
  },
  {
    id: '63',
    directoryName: 'Paws & Effect',
    url: 'https://www.paws-and-effect.com',
    domainAuthority: 66,
    status: 'pending',
    submissionDate: new Date('2024-02-02'),
    focusArea: 'Pets',
  },
  {
    id: '64',
    directoryName: 'All About Cats',
    url: 'https://allaboutcats.com',
    domainAuthority: 71,
    status: 'pending',
    submissionDate: new Date('2024-02-02'),
    focusArea: 'Pets',
  },
  {
    id: '65',
    directoryName: 'Cat Behavior Associates',
    url: 'https://catbehaviorassociates.com',
    domainAuthority: 64,
    status: 'pending',
    submissionDate: new Date('2024-02-02'),
    focusArea: 'Pets',
  },
  {
    id: '66',
    directoryName: 'Houzz',
    url: 'https://www.houzz.com',
    domainAuthority: 94,
    status: 'pending',
    submissionDate: new Date('2024-02-02'),
    focusArea: 'Niche',
  },
  {
    id: '67',
    directoryName: 'Apartment Therapy',
    url: 'https://www.apartmenttherapy.com',
    domainAuthority: 88,
    status: 'pending',
    submissionDate: new Date('2024-02-02'),
    focusArea: 'Niche',
  },
  {
    id: '68',
    directoryName: 'The Kitchn',
    url: 'https://www.thekitchn.com',
    domainAuthority: 86,
    status: 'pending',
    submissionDate: new Date('2024-02-02'),
    focusArea: 'Niche',
  },
  {
    id: '69',
    directoryName: 'BuzzFeed Pets',
    url: 'https://www.buzzfeed.com/animals',
    domainAuthority: 95,
    status: 'pending',
    submissionDate: new Date('2024-02-02'),
    focusArea: 'Pets',
  },
  {
    id: '70',
    directoryName: 'Bored Panda Cats',
    url: 'https://www.boredpanda.com/tag/cats',
    domainAuthority: 90,
    status: 'pending',
    submissionDate: new Date('2024-02-02'),
    focusArea: 'Pets',
  },
  
  // E-commerce & Marketplaces
  {
    id: '71',
    directoryName: 'Amazon',
    url: 'https://www.amazon.com',
    domainAuthority: 98,
    status: 'pending',
    submissionDate: new Date('2024-02-03'),
    focusArea: 'Product',
  },
  {
    id: '72',
    directoryName: 'Etsy',
    url: 'https://www.etsy.com',
    domainAuthority: 94,
    status: 'pending',
    submissionDate: new Date('2024-02-03'),
    focusArea: 'Product',
  },
  {
    id: '73',
    directoryName: 'eBay',
    url: 'https://www.ebay.com',
    domainAuthority: 96,
    status: 'pending',
    submissionDate: new Date('2024-02-03'),
    focusArea: 'Product',
  },
  {
    id: '74',
    directoryName: 'Walmart Marketplace',
    url: 'https://marketplace.walmart.com',
    domainAuthority: 95,
    status: 'pending',
    submissionDate: new Date('2024-02-03'),
    focusArea: 'Product',
  },
  {
    id: '75',
    directoryName: 'Target Plus',
    url: 'https://www.target.com',
    domainAuthority: 93,
    status: 'pending',
    submissionDate: new Date('2024-02-03'),
    focusArea: 'Product',
  },
  
  // Tech & Innovation
  {
    id: '76',
    directoryName: 'TechCrunch',
    url: 'https://techcrunch.com',
    domainAuthority: 95,
    status: 'pending',
    submissionDate: new Date('2024-02-04'),
    focusArea: 'Startup',
  },
  {
    id: '77',
    directoryName: 'VentureBeat',
    url: 'https://venturebeat.com',
    domainAuthority: 92,
    status: 'pending',
    submissionDate: new Date('2024-02-04'),
    focusArea: 'Startup',
  },
  {
    id: '78',
    directoryName: 'The Verge',
    url: 'https://www.theverge.com',
    domainAuthority: 94,
    status: 'pending',
    submissionDate: new Date('2024-02-04'),
    focusArea: 'Product',
  },
  {
    id: '79',
    directoryName: 'Wired',
    url: 'https://www.wired.com',
    domainAuthority: 93,
    status: 'pending',
    submissionDate: new Date('2024-02-04'),
    focusArea: 'Product',
  },
  {
    id: '80',
    directoryName: 'Fast Company',
    url: 'https://www.fastcompany.com',
    domainAuthority: 92,
    status: 'pending',
    submissionDate: new Date('2024-02-04'),
    focusArea: 'Startup',
  },
  
  // More Niche Directories
  {
    id: '81',
    directoryName: 'Sitejabber',
    url: 'https://www.sitejabber.com',
    domainAuthority: 80,
    status: 'pending',
    submissionDate: new Date('2024-02-05'),
    focusArea: 'Review',
  },
  {
    id: '82',
    directoryName: 'Better Business Bureau',
    url: 'https://www.bbb.org',
    domainAuthority: 96,
    status: 'pending',
    submissionDate: new Date('2024-02-05'),
    focusArea: 'Review',
  },
  {
    id: '83',
    directoryName: 'Consumer Affairs',
    url: 'https://www.consumeraffairs.com',
    domainAuthority: 87,
    status: 'pending',
    submissionDate: new Date('2024-02-05'),
    focusArea: 'Review',
  },
  {
    id: '84',
    directoryName: 'Trustradius',
    url: 'https://www.trustradius.com',
    domainAuthority: 78,
    status: 'pending',
    submissionDate: new Date('2024-02-05'),
    focusArea: 'Review',
  },
  {
    id: '85',
    directoryName: 'PeerSpot',
    url: 'https://www.peerspot.com',
    domainAuthority: 76,
    status: 'pending',
    submissionDate: new Date('2024-02-05'),
    focusArea: 'Review',
  },
  {
    id: '86',
    directoryName: 'Gartner Peer Insights',
    url: 'https://www.gartner.com/reviews',
    domainAuthority: 94,
    status: 'pending',
    submissionDate: new Date('2024-02-05'),
    focusArea: 'Review',
  },
  {
    id: '87',
    directoryName: 'FinancesOnline',
    url: 'https://financesonline.com',
    domainAuthority: 79,
    status: 'pending',
    submissionDate: new Date('2024-02-05'),
    focusArea: 'Product',
  },
  {
    id: '88',
    directoryName: 'SourceForge',
    url: 'https://sourceforge.net',
    domainAuthority: 91,
    status: 'pending',
    submissionDate: new Date('2024-02-05'),
    focusArea: 'Product',
  },
  {
    id: '89',
    directoryName: 'GitHub',
    url: 'https://github.com',
    domainAuthority: 96,
    status: 'pending',
    submissionDate: new Date('2024-02-05'),
    focusArea: 'Product',
  },
  {
    id: '90',
    directoryName: 'GitLab',
    url: 'https://gitlab.com',
    domainAuthority: 90,
    status: 'pending',
    submissionDate: new Date('2024-02-05'),
    focusArea: 'Product',
  },
  
  // Canadian Specific
  {
    id: '91',
    directoryName: 'Canada411',
    url: 'https://www.canada411.ca',
    domainAuthority: 75,
    status: 'pending',
    submissionDate: new Date('2024-02-06'),
    focusArea: 'Local',
  },
  {
    id: '92',
    directoryName: 'YellowPages.ca',
    url: 'https://www.yellowpages.ca',
    domainAuthority: 78,
    status: 'pending',
    submissionDate: new Date('2024-02-06'),
    focusArea: 'Local',
  },
  {
    id: '93',
    directoryName: 'Canadian Business Directory',
    url: 'https://www.canadianbusinessdirectory.ca',
    domainAuthority: 65,
    status: 'pending',
    submissionDate: new Date('2024-02-06'),
    focusArea: 'Local',
  },
  {
    id: '94',
    directoryName: 'Canpages',
    url: 'https://www.canpages.ca',
    domainAuthority: 68,
    status: 'pending',
    submissionDate: new Date('2024-02-06'),
    focusArea: 'Local',
  },
  {
    id: '95',
    directoryName: '411.ca',
    url: 'https://www.411.ca',
    domainAuthority: 72,
    status: 'pending',
    submissionDate: new Date('2024-02-06'),
    focusArea: 'Local',
  },
  
  // More Product & Tech
  {
    id: '96',
    directoryName: 'AppSumo',
    url: 'https://appsumo.com',
    domainAuthority: 82,
    status: 'pending',
    submissionDate: new Date('2024-02-07'),
    focusArea: 'Product',
  },
  {
    id: '97',
    directoryName: 'Pitchground',
    url: 'https://pitchground.com',
    domainAuthority: 68,
    status: 'pending',
    submissionDate: new Date('2024-02-07'),
    focusArea: 'Product',
  },
  {
    id: '98',
    directoryName: 'DealFuel',
    url: 'https://dealfuel.com',
    domainAuthority: 64,
    status: 'pending',
    submissionDate: new Date('2024-02-07'),
    focusArea: 'Product',
  },
  {
    id: '99',
    directoryName: 'StackSocial',
    url: 'https://stacksocial.com',
    domainAuthority: 76,
    status: 'pending',
    submissionDate: new Date('2024-02-07'),
    focusArea: 'Product',
  },
  {
    id: '100',
    directoryName: 'Mighty Deals',
    url: 'https://mightydeals.com',
    domainAuthority: 70,
    status: 'pending',
    submissionDate: new Date('2024-02-07'),
    focusArea: 'Product',
  },
  
  // Content & Media
  {
    id: '105',
    directoryName: 'Pinterest',
    url: 'https://www.pinterest.com',
    domainAuthority: 95,
    status: 'pending',
    submissionDate: new Date('2024-02-08'),
    focusArea: 'Community',
  },
  {
    id: '106',
    directoryName: 'Tumblr',
    url: 'https://www.tumblr.com',
    domainAuthority: 99,
    status: 'pending',
    submissionDate: new Date('2024-02-08'),
    focusArea: 'Community',
  },
  {
    id: '107',
    directoryName: 'Flipboard',
    url: 'https://flipboard.com',
    domainAuthority: 92,
    status: 'pending',
    submissionDate: new Date('2024-02-08'),
    focusArea: 'Community',
  },
  {
    id: '108',
    directoryName: 'Mix',
    url: 'https://mix.com',
    domainAuthority: 88,
    status: 'pending',
    submissionDate: new Date('2024-02-08'),
    focusArea: 'Community',
  },
  {
    id: '109',
    directoryName: 'Pocket',
    url: 'https://getpocket.com',
    domainAuthority: 93,
    status: 'pending',
    submissionDate: new Date('2024-02-08'),
    focusArea: 'Community',
  },
  {
    id: '110',
    directoryName: 'Feedly',
    url: 'https://feedly.com',
    domainAuthority: 90,
    status: 'pending',
    submissionDate: new Date('2024-02-08'),
    focusArea: 'Community',
  },
  
  // More Startup & Business
  {
    id: '111',
    directoryName: 'Startups.co',
    url: 'https://www.startups.co',
    domainAuthority: 74,
    status: 'pending',
    submissionDate: new Date('2024-02-09'),
    focusArea: 'Startup',
  },
  {
    id: '112',
    directoryName: 'Startup Grind',
    url: 'https://www.startupgrind.com',
    domainAuthority: 80,
    status: 'pending',
    submissionDate: new Date('2024-02-09'),
    focusArea: 'Startup',
  },
  {
    id: '113',
    directoryName: 'Startup Nation',
    url: 'https://startupnation.com',
    domainAuthority: 72,
    status: 'pending',
    submissionDate: new Date('2024-02-09'),
    focusArea: 'Startup',
  },
  {
    id: '114',
    directoryName: 'Entrepreneur',
    url: 'https://www.entrepreneur.com',
    domainAuthority: 93,
    status: 'pending',
    submissionDate: new Date('2024-02-09'),
    focusArea: 'Startup',
  },
  {
    id: '115',
    directoryName: 'Inc.com',
    url: 'https://www.inc.com',
    domainAuthority: 94,
    status: 'pending',
    submissionDate: new Date('2024-02-09'),
    focusArea: 'Startup',
  },
  {
    id: '116',
    directoryName: 'Forbes',
    url: 'https://www.forbes.com',
    domainAuthority: 95,
    status: 'pending',
    submissionDate: new Date('2024-02-09'),
    focusArea: 'Startup',
  },
  {
    id: '117',
    directoryName: 'Business Insider',
    url: 'https://www.businessinsider.com',
    domainAuthority: 94,
    status: 'pending',
    submissionDate: new Date('2024-02-09'),
    focusArea: 'Startup',
  },
  {
    id: '118',
    directoryName: 'Mashable',
    url: 'https://mashable.com',
    domainAuthority: 93,
    status: 'pending',
    submissionDate: new Date('2024-02-09'),
    focusArea: 'Product',
  },
  {
    id: '119',
    directoryName: 'Lifehacker',
    url: 'https://lifehacker.com',
    domainAuthority: 91,
    status: 'pending',
    submissionDate: new Date('2024-02-09'),
    focusArea: 'Product',
  },
  {
    id: '120',
    directoryName: 'Gizmodo',
    url: 'https://gizmodo.com',
    domainAuthority: 92,
    status: 'pending',
    submissionDate: new Date('2024-02-09'),
    focusArea: 'Product',
  },
  
  // Additional Pet & Lifestyle
  {
    id: '121',
    directoryName: 'Modern Cat Magazine',
    url: 'https://moderncat.com',
    domainAuthority: 67,
    status: 'pending',
    submissionDate: new Date('2024-02-10'),
    focusArea: 'Pets',
  },
  {
    id: '122',
    directoryName: 'Cat Fancy',
    url: 'https://catfancy.com',
    domainAuthority: 65,
    status: 'pending',
    submissionDate: new Date('2024-02-10'),
    focusArea: 'Pets',
  },
  {
    id: '123',
    directoryName: 'Catnip Times',
    url: 'https://catniptimes.com',
    domainAuthority: 62,
    status: 'pending',
    submissionDate: new Date('2024-02-10'),
    focusArea: 'Pets',
  },
  {
    id: '124',
    directoryName: 'Meow Lifestyle',
    url: 'https://meowlifestyle.com',
    domainAuthority: 60,
    status: 'pending',
    submissionDate: new Date('2024-02-10'),
    focusArea: 'Pets',
  },
  {
    id: '125',
    directoryName: 'Purr World',
    url: 'https://purrworld.com',
    domainAuthority: 58,
    status: 'pending',
    submissionDate: new Date('2024-02-10'),
    focusArea: 'Pets',
  },
  {
    id: '126',
    directoryName: 'Feline Living',
    url: 'https://felineliving.net',
    domainAuthority: 64,
    status: 'pending',
    submissionDate: new Date('2024-02-10'),
    focusArea: 'Pets',
  },
  {
    id: '127',
    directoryName: 'Senior Cat Wellness',
    url: 'https://seniorcatwellness.com',
    domainAuthority: 61,
    status: 'pending',
    submissionDate: new Date('2024-02-10'),
    focusArea: 'Pets',
  },
  {
    id: '128',
    directoryName: 'Excited Cats',
    url: 'https://excitedcats.com',
    domainAuthority: 66,
    status: 'pending',
    submissionDate: new Date('2024-02-10'),
    focusArea: 'Pets',
  },
  {
    id: '129',
    directoryName: 'Hepper',
    url: 'https://www.hepper.com',
    domainAuthority: 68,
    status: 'pending',
    submissionDate: new Date('2024-02-10'),
    focusArea: 'Pets',
  },
  {
    id: '130',
    directoryName: 'Pet Keen',
    url: 'https://petkeen.com',
    domainAuthority: 70,
    status: 'pending',
    submissionDate: new Date('2024-02-10'),
    focusArea: 'Pets',
  },
  
  // Final Batch - Niche & Emerging
  {
    id: '131',
    directoryName: 'Microacquire',
    url: 'https://microacquire.com',
    domainAuthority: 73,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Startup',
  },
  {
    id: '132',
    directoryName: 'Acquire.com',
    url: 'https://acquire.com',
    domainAuthority: 71,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Startup',
  },
  {
    id: '133',
    directoryName: 'Flippa',
    url: 'https://flippa.com',
    domainAuthority: 79,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Startup',
  },
  {
    id: '134',
    directoryName: 'Empire Flippers',
    url: 'https://empireflippers.com',
    domainAuthority: 75,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Startup',
  },
  {
    id: '135',
    directoryName: 'FE International',
    url: 'https://feinternational.com',
    domainAuthority: 69,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Startup',
  },
  {
    id: '136',
    directoryName: 'Shopify App Store',
    url: 'https://apps.shopify.com',
    domainAuthority: 94,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Product',
  },
  {
    id: '137',
    directoryName: 'WordPress Plugin Directory',
    url: 'https://wordpress.org/plugins',
    domainAuthority: 98,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Product',
  },
  {
    id: '138',
    directoryName: 'Chrome Web Store',
    url: 'https://chrome.google.com/webstore',
    domainAuthority: 100,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Product',
  },
  {
    id: '139',
    directoryName: 'Firefox Add-ons',
    url: 'https://addons.mozilla.org',
    domainAuthority: 97,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Product',
  },
  {
    id: '140',
    directoryName: 'Zapier App Directory',
    url: 'https://zapier.com/apps',
    domainAuthority: 93,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Product',
  },
  {
    id: '141',
    directoryName: 'Make (Integromat)',
    url: 'https://www.make.com',
    domainAuthority: 85,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Product',
  },
  {
    id: '142',
    directoryName: 'Pabbly Connect',
    url: 'https://www.pabbly.com/connect',
    domainAuthority: 72,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Product',
  },
  {
    id: '143',
    directoryName: 'Integrately',
    url: 'https://integrately.com',
    domainAuthority: 68,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Product',
  },
  {
    id: '144',
    directoryName: 'n8n',
    url: 'https://n8n.io',
    domainAuthority: 74,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Product',
  },
  {
    id: '145',
    directoryName: 'Airtable Universe',
    url: 'https://www.airtable.com/universe',
    domainAuthority: 92,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Product',
  },
  {
    id: '146',
    directoryName: 'Notion Template Gallery',
    url: 'https://www.notion.so/templates',
    domainAuthority: 94,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Product',
  },
  {
    id: '147',
    directoryName: 'Coda Gallery',
    url: 'https://coda.io/gallery',
    domainAuthority: 82,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Product',
  },
  {
    id: '148',
    directoryName: 'Webflow Showcase',
    url: 'https://webflow.com/made-in-webflow',
    domainAuthority: 91,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Product',
  },
  {
    id: '149',
    directoryName: 'Framer Community',
    url: 'https://www.framer.com/community',
    domainAuthority: 86,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Product',
  },
  {
    id: '150',
    directoryName: 'Figma Community',
    url: 'https://www.figma.com/community',
    domainAuthority: 93,
    status: 'pending',
    submissionDate: new Date('2024-02-11'),
    focusArea: 'Product',
  },
];

export const mockAutomationTasks: AutomationTask[] = [
  {
    id: 'auto-1',
    name: 'Essential listings refresh',
    cadence: 'monthly',
    nextRun: new Date('2024-02-01'),
    owner: 'Automation Engine',
    status: 'scheduled',
    impact: 'critical',
    relatedDirectories: ['Google Business Profile', 'Yelp', 'Bing Places'],
    notes: 'Sync NAP, photos, service area across top local profiles.',
  },
  {
    id: 'auto-2',
    name: 'Social storytelling cadence',
    cadence: 'weekly',
    nextRun: new Date('2024-01-31'),
    owner: 'Content Studio',
    status: 'scheduled',
    impact: 'high',
    relatedDirectories: ['Instagram', 'TikTok', 'YouTube Channel'],
    notes: 'Plan reels, shorts, and long-form demos focused on cat odor control.',
  },
  {
    id: 'auto-3',
    name: 'Review generation workflow',
    cadence: 'monthly',
    nextRun: new Date('2024-02-05'),
    owner: 'Customer Success',
    status: 'in-progress',
    impact: 'high',
    relatedDirectories: ['Trustpilot Reviews', 'Google Business Profile'],
    notes: 'Email post-purchase customers requesting verified odor-improvement stories.',
  },
  {
    id: 'auto-4',
    name: 'Cat community outreach',
    cadence: 'weekly',
    nextRun: new Date('2024-02-02'),
    owner: 'Partnerships',
    status: 'scheduled',
    impact: 'medium',
    relatedDirectories: ['Catster', 'Love Meow', 'Modern Cat Magazine'],
    notes: 'Pitch educational pieces and giveaways to feline publishers.',
  },
];

export const mockSeoTasks: SeoTask[] = [
  {
    id: 'task-1',
    label: 'Refresh Yelp and Bing listings with new imagery',
    category: 'Listing',
    impactScore: 92,
    status: 'active',
    owner: 'Brand Ops',
    dueDate: new Date('2024-02-03'),
  },
  {
    id: 'task-2',
    label: 'Pitch Catster and Love Meow editorial features',
    category: 'Content',
    impactScore: 90,
    status: 'queued',
    owner: 'PR Team',
    dueDate: new Date('2024-02-07'),
  },
  {
    id: 'task-3',
    label: 'Collect 15 new Trustpilot reviews from recent buyers',
    category: 'Review',
    impactScore: 88,
    status: 'active',
    owner: 'Customer Success',
    dueDate: new Date('2024-02-12'),
  },
  {
    id: 'task-4',
    label: 'Launch Amazon storefront with optimized A+ content',
    category: 'Listing',
    impactScore: 86,
    status: 'queued',
    owner: 'Ecommerce Ops',
    dueDate: new Date('2024-02-15'),
  },
  {
    id: 'task-5',
    label: 'Publish welcome series on Purrify Substack',
    category: 'Content',
    impactScore: 80,
    status: 'queued',
    owner: 'Content Studio',
    dueDate: new Date('2024-02-18'),
  },
];

// Mock data for duplicate detections
export const mockDuplicateDetections: DuplicateDetection[] = [
  {
    id: '1',
    directoryName: 'StartupBase',
    url: 'https://startupbase.io',
    confidenceScore: 0.95,
    detectedDate: new Date('2024-01-23'),
    status: 'pending',
  },
  {
    id: '2',
    directoryName: 'SaaSHub',
    url: 'https://saashub.com',
    confidenceScore: 0.78,
    detectedDate: new Date('2024-01-24'),
    status: 'pending',
  },
  {
    id: '3',
    directoryName: 'Capterra',
    url: 'https://capterra.com',
    confidenceScore: 0.62,
    detectedDate: new Date('2024-01-25'),
    status: 'accepted',
  },
];

// Mock data for blog contacts
export const mockBlogContacts: BlogContact[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah@techblog.com',
    blogUrl: 'https://techblog.com',
    domainAuthority: 78,
    status: 'responded',
    lastContactDate: new Date('2024-01-20'),
    notes: 'Interested in guest post collaboration',
  },
  {
    id: '2',
    name: 'Mike Chen',
    email: 'mike@startupinsights.io',
    blogUrl: 'https://startupinsights.io',
    domainAuthority: 82,
    status: 'contacted',
    lastContactDate: new Date('2024-01-22'),
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily@devnews.com',
    blogUrl: 'https://devnews.com',
    domainAuthority: 85,
    status: 'new',
  },
  {
    id: '4',
    name: 'David Park',
    email: 'david@saasnews.net',
    blogUrl: 'https://saasnews.net',
    domainAuthority: 76,
    status: 'declined',
    lastContactDate: new Date('2024-01-15'),
    notes: 'Not accepting guest posts currently',
  },
];

// Mock data for outreach templates
export const mockOutreachTemplates: OutreachTemplate[] = [
  {
    id: '1',
    name: 'Initial Outreach',
    subject: 'Guest Post Opportunity for {{blog_name}}',
    body: 'Hi {{contact_name}},\n\nI hope this email finds you well. I\'ve been following {{blog_name}} and really appreciate your content on {{topic}}.\n\nI\'d love to contribute a guest post...',
    category: 'Guest Post',
  },
  {
    id: '2',
    name: 'Follow-up',
    subject: 'Following up on guest post opportunity',
    body: 'Hi {{contact_name}},\n\nI wanted to follow up on my previous email about contributing to {{blog_name}}...',
    category: 'Follow-up',
  },
  {
    id: '3',
    name: 'Product Feature Request',
    subject: 'Feature opportunity: {{product_name}}',
    body: 'Hi {{contact_name}},\n\nI noticed you recently covered {{related_topic}} on {{blog_name}}. I thought you might be interested in {{product_name}}...',
    category: 'Product Feature',
  },
];

export const mockAiSummary: AiGenerationSummary = {
  totalDirectories: mockDirectorySubmissions.length,
  uniqueDescriptions: mockDirectorySubmissions.filter((submission) => submission.aiStatus === 'generated').length,
  averageTokens: 365,
  lastRun: new Date('2024-01-26T10:30:00Z'),
  model: 'claude-3-opus',
};