import {
  DirectorySubmission,
  DuplicateDetection,
  BlogContact,
  OutreachTemplate,
  AutomationTask,
  SeoTask,
  AiGenerationSummary,
} from '@/types';

// Priority directory and community placements for Purrify
export const mockDirectorySubmissions: DirectorySubmission[] = [
  // Tier 1: Essential (DA 90+)
  {
    id: '1',
    directoryName: 'Google Business Profile',
    url: 'https://business.google.com',
    domainAuthority: 100,
    status: 'approved',
    submissionDate: new Date('2024-01-15'),
    nextResubmission: new Date('2024-02-01'),
    tier: 'Essential',
    focusArea: 'Local',
    automation: 'auto',
    notes: 'Auto-sync NAP monthly; monitor for review responses. Review link https://g.page/r/CUB8bZ_ibMbwEBI/review.',
    aiDescription:
      'Elevate local visibility with a complete Google My Business profile featuring verified NAP data, service categories, and fresh media.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-25T10:12:00Z'),
    anthropicModel: 'claude-3-opus',
  },
  {
    id: '2',
    directoryName: 'Yelp',
    url: 'https://yelp.com',
    domainAuthority: 94,
    status: 'approved',
    submissionDate: new Date('2024-01-15'),
    nextResubmission: new Date('2024-02-03'),
    tier: 'Essential',
    focusArea: 'Local',
    automation: 'auto',
    notes: 'Push latest photos via automation workflow. Settings portal https://biz.yelp.com/settings.',
    aiDescription:
      'Stand out on Yelp with an optimized description that highlights customer wins, rapid response times, and top-tier support ratings.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-25T10:14:00Z'),
    anthropicModel: 'claude-3-opus',
  },
  {
    id: '3',
    directoryName: 'Trustpilot Reviews',
    url: 'https://www.trustpilot.com/review/purrify.ca',
    domainAuthority: 89,
    status: 'approved',
    submissionDate: new Date('2024-01-15'),
    tier: 'High Impact',
    focusArea: 'Review',
    notes: 'Review page is live; continue requesting verified customer feedback.',
  },
  {
    id: '6',
    directoryName: 'Facebook Page',
    url: 'https://www.facebook.com/purrifyhq',
    domainAuthority: 96,
    status: 'pending',
    submissionDate: new Date('2024-01-28'),
    tier: 'Essential',
    focusArea: 'Community',
    notes: 'Drafting launch content and community guidelines before publishing.',
  },
  {
    id: '7',
    directoryName: 'LinkedIn Company',
    url: 'https://linkedin.com',
    domainAuthority: 98,
    status: 'approved',
    submissionDate: new Date('2024-01-12'),
    nextResubmission: new Date('2024-02-09'),
    tier: 'Essential',
    focusArea: 'Community',
    automation: 'auto',
    notes: 'Auto-sync employee count and tagline monthly.',
    aiDescription:
      'Position the team as growth-minded operators scaling AI-driven SEO automation for GTM leaders worldwide.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-25T11:05:00Z'),
    anthropicModel: 'claude-3-opus',
  },
  // Essential social channels marked complete
  {
    id: '101',
    directoryName: 'X (Twitter)',
    url: 'https://x.com/PurrifyHQ',
    domainAuthority: 94,
    status: 'approved',
    submissionDate: new Date('2024-01-26'),
    nextResubmission: new Date('2024-02-20'),
    tier: 'Essential',
    focusArea: 'Community',
    automation: 'manual',
    notes: 'Live handle; monitor mentions daily and pin launch thread.',
    aiDescription:
      'Keep the feed active with ship logs, customer love, and fast replies to inbound questions.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-26T16:40:00Z'),
    anthropicModel: 'claude-3-sonnet',
  },
  {
    id: '102',
    directoryName: 'Instagram',
    url: 'https://www.instagram.com/purrifyhq/',
    domainAuthority: 96,
    status: 'approved',
    submissionDate: new Date('2024-01-26'),
    nextResubmission: new Date('2024-02-22'),
    tier: 'Essential',
    focusArea: 'Community',
    automation: 'manual',
    notes: 'Profile live with hero assets; schedule weekly reels.',
    aiDescription:
      'Highlight behind-the-scenes product walkthroughs and customer pets to stay on brand.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-26T16:45:00Z'),
    anthropicModel: 'claude-3-haiku',
  },
  {
    id: '103',
    directoryName: 'TikTok',
    url: 'https://www.tiktok.com/@purrifyhq',
    domainAuthority: 92,
    status: 'approved',
    submissionDate: new Date('2024-01-26'),
    nextResubmission: new Date('2024-02-24'),
    tier: 'High Impact',
    focusArea: 'Community',
    automation: 'manual',
    notes: 'Short-form intro published; monitor comments.',
    aiDescription:
      'Publish playful micro-demos and customer stories to tap into discovery traffic.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-26T16:50:00Z'),
    anthropicModel: 'claude-3-haiku',
  },
  {
    id: '104',
    directoryName: 'YouTube Channel',
    url: 'https://www.youtube.com/@PurrifyHQ',
    domainAuthority: 100,
    status: 'approved',
    submissionDate: new Date('2024-01-26'),
    nextResubmission: new Date('2024-02-28'),
    tier: 'Essential',
    focusArea: 'Community',
    automation: 'manual',
    notes: 'Channel art live; upload cadence every other week.',
    aiDescription:
      'Anchor long-form demos and testimonials to nurture high-intent evaluators.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-26T16:55:00Z'),
    anthropicModel: 'claude-3-opus',
  },
  {
    id: '8',
    directoryName: 'Apple Maps',
    url: 'https://mapsconnect.apple.com',
    domainAuthority: 100,
    status: 'approved',
    submissionDate: new Date('2024-01-18'),
    nextResubmission: new Date('2024-02-11'),
    tier: 'Essential',
    focusArea: 'Local',
    automation: 'auto',
    notes: 'Monthly sync to maintain pin accuracy.',
    aiDescription:
      'Guide iOS searchers to accurate contact info, storefront details, and up-to-date appointment links.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-25T10:18:00Z'),
    anthropicModel: 'claude-3-haiku',
  },
  {
    id: '9',
    directoryName: 'Bing Places',
    url: 'https://bingplaces.com',
    domainAuthority: 93,
    status: 'approved',
    submissionDate: new Date('2024-01-14'),
    nextResubmission: new Date('2024-02-07'),
    tier: 'Essential',
    focusArea: 'Local',
    automation: 'auto',
    notes: 'Synced alongside GMB push; verified via https://www.bing.com/forbusiness/singleEntity?bizid=dc537d86-4d9b-47d2-9c8f-5019712edd9f.',
    aiDescription:
      'Mirror the high-intent messaging from GMB while reinforcing Microsoft ecosystem coverage.',
    aiStatus: 'generated',
    lastAiGeneration: new Date('2024-01-25T10:20:00Z'),
    anthropicModel: 'claude-3-haiku',
  },
  {
    id: '10',
    directoryName: 'Medium Profile',
    url: 'https://medium.com/@purrify',
    domainAuthority: 96,
    status: 'approved',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Community',
    notes: 'Published launch story and product education for cat owners.',
  },
  {
    id: '11',
    directoryName: 'Whop Marketplace Listing',
    url: 'https://whop.com/purrify',
    domainAuthority: 72,
    status: 'approved',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Product',
    notes: 'Digital storefront live with onboarding assets and FAQs.',
  },
  {
    id: '12',
    directoryName: 'Purrify Substack',
    url: 'https://purrifyhq.substack.com',
    domainAuthority: 88,
    status: 'pending',
    submissionDate: new Date('2024-01-28'),
    focusArea: 'Community',
    notes: 'Building welcome sequence and editorial calendar prior to launch.',
  },
  {
    id: '13',
    directoryName: 'Amazon Storefront',
    url: 'https://www.amazon.com/stores/purrify',
    domainAuthority: 96,
    status: 'pending',
    submissionDate: new Date('2024-01-28'),
    focusArea: 'Product',
    notes: 'Awaiting compliance review for product detail pages.',
  },

  // Cat owner outreach network
  {
    id: '107',
    directoryName: 'Catster',
    url: 'https://www.catster.com',
    domainAuthority: 82,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Feature Purrify in Catster lifestyle stories for reach among cat adopters.',
  },
  {
    id: '108',
    directoryName: 'The Cat Site',
    url: 'https://thecatsite.com',
    domainAuthority: 77,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Partner on forum AMAs about SEO for boutique pet brands.',
  },
  {
    id: '109',
    directoryName: 'Modern Cat Magazine',
    url: 'https://moderncat.com',
    domainAuthority: 74,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Pitch guest article on building local search visibility for cat cafes.',
  },
  {
    id: '110',
    directoryName: 'Adventure Cats',
    url: 'https://www.adventurecats.org',
    domainAuthority: 64,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Highlight travel-friendly brand listings for outdoor cat guardians.',
  },
  {
    id: '111',
    directoryName: 'Purrington Post',
    url: 'https://www.purringtonpost.com',
    domainAuthority: 61,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Submit founder Q&A on automating directory updates for pet retailers.',
  },
  {
    id: '112',
    directoryName: 'Meowingtons Blog',
    url: 'https://www.meowingtons.com/blogs/news',
    domainAuthority: 67,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Secure sponsored content on DTC launch playbooks for cat brands.',
  },
  {
    id: '113',
    directoryName: 'Love Meow',
    url: 'https://www.lovemeow.com',
    domainAuthority: 79,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Share case study on boosting rescue visibility with directory coverage.',
  },
  {
    id: '114',
    directoryName: 'iHeartCats',
    url: 'https://iheartcats.com',
    domainAuthority: 70,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Create co-branded guide on fundraising funnels for shelters.',
  },
  {
    id: '115',
    directoryName: 'The Conscious Cat',
    url: 'https://consciouscat.net',
    domainAuthority: 63,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Offer expert column on ethical SEO for holistic pet care.',
  },
  {
    id: '116',
    directoryName: 'Cat Friendly Homes',
    url: 'https://catfriendly.com',
    domainAuthority: 68,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Promote compliance checklist for veterinary directory listings.',
  },
  {
    id: '117',
    directoryName: 'Feline Living',
    url: 'https://www.felineliving.net',
    domainAuthority: 62,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Guest tutorial on mapping keywords to cat care buyer journeys.',
  },
  {
    id: '118',
    directoryName: 'CatWorld',
    url: 'https://www.catworld.com.au',
    domainAuthority: 58,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Localize listing recommendations for ANZ cat services.',
  },
  {
    id: '119',
    directoryName: 'Cat Lovers Only',
    url: 'https://www.catloversonly.com',
    domainAuthority: 56,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Spotlight checklist for indie cat shop directory hygiene.',
  },
  {
    id: '120',
    directoryName: 'CatTime',
    url: 'https://cattime.com',
    domainAuthority: 74,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Publish trends report on search demand for cat wellness products.',
  },
  {
    id: '121',
    directoryName: 'Petfinder Cats',
    url: 'https://www.petfinder.com/cats',
    domainAuthority: 88,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Align adoption partners with accurate location data feeds.',
  },
  {
    id: '122',
    directoryName: 'Chewy Cat Central',
    url: 'https://be.chewy.com/cat',
    domainAuthority: 84,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Co-author sponsored lesson on product-led directory launches.',
  },
  {
    id: '123',
    directoryName: 'Petco Cat Care',
    url: 'https://www.petco.com/cat-care',
    domainAuthority: 86,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Share syndication plan for multi-location cat grooming brands.',
  },
  {
    id: '124',
    directoryName: 'PetSmart Cat Resource',
    url: 'https://www.petsmart.com/learn/cat',
    domainAuthority: 83,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Secure educational listing for in-store cat adoption events.',
  },
  {
    id: '125',
    directoryName: 'Tuft + Paw Journal',
    url: 'https://www.tuftandpaw.com/blogs/journal',
    domainAuthority: 60,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Pitch content on design-led SEO for modern cat furniture brands.',
  },
  {
    id: '126',
    directoryName: 'Modkat Blog',
    url: 'https://blog.modkat.com',
    domainAuthority: 57,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Offer data story on litter box buyers via directory analytics.',
  },
  {
    id: '127',
    directoryName: 'Hauspanther',
    url: 'https://www.hauspanther.com',
    domainAuthority: 66,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Feature portfolio of automated listings for boutique cat brands.',
  },
  {
    id: '128',
    directoryName: 'Litter-Robot Blog',
    url: 'https://www.litter-robot.com/blog',
    domainAuthority: 73,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Publish automation case study for smart litter tech companies.',
  },
  {
    id: '129',
    directoryName: 'KittyClysm',
    url: 'https://kittyclysm.com',
    domainAuthority: 54,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Education piece on keyword research for cat bloggers.',
  },
  {
    id: '130',
    directoryName: 'Cat Behavior Associates',
    url: 'https://www.catbehaviorassociates.com/blog',
    domainAuthority: 59,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Outline structured data tips for behavior consultants.',
  },
  {
    id: '131',
    directoryName: 'Cat Wisdom 101',
    url: 'https://catwisdom101.com',
    domainAuthority: 55,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Amplify wellness-focused listings for senior cat care.',
  },
  {
    id: '132',
    directoryName: 'Pawsome Kitty',
    url: 'https://www.pawsomekitty.com',
    domainAuthority: 52,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Guest article on micro-influencer outreach for cat boutiques.',
  },
  {
    id: '133',
    directoryName: 'The Catnip Times',
    url: 'https://www.thecatniptimes.com',
    domainAuthority: 65,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Plan editorial takeover timed with National Cat Day.',
  },
  {
    id: '134',
    directoryName: 'Jackson Galaxy Blog',
    url: 'https://www.jacksongalaxy.com/blogs/blog',
    domainAuthority: 72,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Align behavioral SEO tips with celebrity endorsement.',
  },
  {
    id: '135',
    directoryName: 'Best Friends Cat Program',
    url: 'https://resources.bestfriends.org/cats',
    domainAuthority: 83,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Support national rescue partners with directory templates.',
  },
  {
    id: '136',
    directoryName: 'Alley Cat Allies Blog',
    url: 'https://www.alleycat.org/resources',
    domainAuthority: 80,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Provide advocacy toolkit with local listing guidance.',
  },
  {
    id: '137',
    directoryName: 'Cats Protection Advice',
    url: 'https://www.cats.org.uk/help-and-advice',
    domainAuthority: 88,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Build UK-specific directory map for charity partners.',
  },
  {
    id: '138',
    directoryName: 'ASPCA Cat Care',
    url: 'https://www.aspca.org/pet-care/cat-care',
    domainAuthority: 92,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Align educational resources with automated listing feeds.',
  },
  {
    id: '139',
    directoryName: 'Humane Society Cat Resources',
    url: 'https://www.humanesociety.org/resources/cats',
    domainAuthority: 89,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Provide templated outreach for municipal shelter directories.',
  },
  {
    id: '140',
    directoryName: 'PetMD Cats Library',
    url: 'https://www.petmd.com/cat',
    domainAuthority: 91,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Develop medical SEO checklist for veterinary partners.',
  },
  {
    id: '141',
    directoryName: 'Rover Cats Guide',
    url: 'https://www.rover.com/blog/cats',
    domainAuthority: 88,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Publish marketplace success story leveraging Purrify submissions.',
  },
  {
    id: '142',
    directoryName: 'Wag! Cats Hub',
    url: 'https://wagwalking.com/cat',
    domainAuthority: 75,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Launch joint webinar on SEO for mobile cat services.',
  },
  {
    id: '143',
    directoryName: 'Daily Paws Cats',
    url: 'https://www.dailypaws.com/cats-kittens',
    domainAuthority: 79,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Secure editorial featuring launch of Purrify listings toolkit.',
  },
  {
    id: '144',
    directoryName: 'Martha Stewart Cats',
    url: 'https://www.marthastewart.com/cats',
    domainAuthority: 90,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Contribute home design SEO tips for stylish cat owners.',
  },
  {
    id: '145',
    directoryName: 'Apartment Therapy Cats',
    url: 'https://www.apartmenttherapy.com/collection/pets/cats',
    domainAuthority: 88,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Pitch space-saving directory strategies for urban cat startups.',
  },
  {
    id: '146',
    directoryName: 'Bustle Cats & Pets',
    url: 'https://www.bustle.com/pets/cats',
    domainAuthority: 92,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Coordinate PR feature on AI-powered pet marketing.',
  },
  {
    id: '147',
    directoryName: 'Country Living Cats',
    url: 'https://www.countryliving.com/pets/cats',
    domainAuthority: 87,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Showcase rural success stories using automated listings.',
  },
  {
    id: '148',
    directoryName: 'Catit Community',
    url: 'https://www.catit.com/community',
    domainAuthority: 62,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Collaborate on product education for cat enrichment brands.',
  },
  {
    id: '149',
    directoryName: 'Cole and Marmalade',
    url: 'https://coleandmarmalade.com',
    domainAuthority: 69,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Secure influencer spotlight on polished directory presence.',
  },
  {
    id: '150',
    directoryName: 'We Love Cats and Kittens',
    url: 'https://welovecatsandkittens.com',
    domainAuthority: 71,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Plan newsletter feature on free cat marketing channels.',
  },
  {
    id: '151',
    directoryName: 'KitNipBox Blog',
    url: 'https://www.kitnipbox.com/blogs/kitnip-blog',
    domainAuthority: 57,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Partner on subscription growth checklist for cat boxes.',
  },
  {
    id: '152',
    directoryName: 'Cat Cafe Directory',
    url: 'https://catcafe.directory',
    domainAuthority: 49,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Aggregate global cat cafe listings managed by Purrify.',
  },
  {
    id: '153',
    directoryName: 'Cat Lady Academy',
    url: 'https://catladyacademy.com/blog',
    domainAuthority: 42,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Offer training module on SEO fundamentals for catpreneurs.',
  },
  {
    id: '154',
    directoryName: 'Purrfect Post Blog',
    url: 'https://www.purrfectpost.com/blog',
    domainAuthority: 53,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Educational content on keyword strategy for product pages.',
  },
  {
    id: '155',
    directoryName: 'Meowtel Blog',
    url: 'https://www.meowtel.com/blog',
    domainAuthority: 58,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Profile sitter marketplace success with automation.',
  },
  {
    id: '156',
    directoryName: 'City the Kitty',
    url: 'https://citythekitty.org/blog',
    domainAuthority: 50,
    status: 'pending',
    submissionDate: new Date('2024-01-27'),
    focusArea: 'Pets',
    notes: 'Support advocacy campaigns with optimized resource listings.',
  },
];

export const mockAutomationTasks: AutomationTask[] = [
  {
    id: 'auto-1',
    name: 'Essential listings refresh',
    cadence: 'monthly',
    nextRun: new Date('2024-02-01'),
    owner: 'Automation Engine',
    status: 'scheduled',
    impact: 'critical',
    relatedDirectories: ['Google Business Profile', 'Yelp', 'Bing Places'],
    notes: 'Sync NAP, photos, service area across top local profiles.',
  },
  {
    id: 'auto-2',
    name: 'Social storytelling cadence',
    cadence: 'weekly',
    nextRun: new Date('2024-01-31'),
    owner: 'Content Studio',
    status: 'scheduled',
    impact: 'high',
    relatedDirectories: ['Instagram', 'TikTok', 'YouTube Channel'],
    notes: 'Plan reels, shorts, and long-form demos focused on cat odor control.',
  },
  {
    id: 'auto-3',
    name: 'Review generation workflow',
    cadence: 'monthly',
    nextRun: new Date('2024-02-05'),
    owner: 'Customer Success',
    status: 'in-progress',
    impact: 'high',
    relatedDirectories: ['Trustpilot Reviews', 'Google Business Profile'],
    notes: 'Email post-purchase customers requesting verified odor-improvement stories.',
  },
  {
    id: 'auto-4',
    name: 'Cat community outreach',
    cadence: 'weekly',
    nextRun: new Date('2024-02-02'),
    owner: 'Partnerships',
    status: 'scheduled',
    impact: 'medium',
    relatedDirectories: ['Catster', 'Love Meow', 'Modern Cat Magazine'],
    notes: 'Pitch educational pieces and giveaways to feline publishers.',
  },
];

export const mockSeoTasks: SeoTask[] = [
  {
    id: 'task-1',
    label: 'Refresh Yelp and Bing listings with new imagery',
    category: 'Listing',
    impactScore: 92,
    status: 'active',
    owner: 'Brand Ops',
    dueDate: new Date('2024-02-03'),
  },
  {
    id: 'task-2',
    label: 'Pitch Catster and Love Meow editorial features',
    category: 'Content',
    impactScore: 90,
    status: 'queued',
    owner: 'PR Team',
    dueDate: new Date('2024-02-07'),
  },
  {
    id: 'task-3',
    label: 'Collect 15 new Trustpilot reviews from recent buyers',
    category: 'Review',
    impactScore: 88,
    status: 'active',
    owner: 'Customer Success',
    dueDate: new Date('2024-02-12'),
  },
  {
    id: 'task-4',
    label: 'Launch Amazon storefront with optimized A+ content',
    category: 'Listing',
    impactScore: 86,
    status: 'queued',
    owner: 'Ecommerce Ops',
    dueDate: new Date('2024-02-15'),
  },
  {
    id: 'task-5',
    label: 'Publish welcome series on Purrify Substack',
    category: 'Content',
    impactScore: 80,
    status: 'queued',
    owner: 'Content Studio',
    dueDate: new Date('2024-02-18'),
  },
];

// Mock data for duplicate detections
export const mockDuplicateDetections: DuplicateDetection[] = [
  {
    id: '1',
    directoryName: 'StartupBase',
    url: 'https://startupbase.io',
    confidenceScore: 0.95,
    detectedDate: new Date('2024-01-23'),
    status: 'pending',
  },
  {
    id: '2',
    directoryName: 'SaaSHub',
    url: 'https://saashub.com',
    confidenceScore: 0.78,
    detectedDate: new Date('2024-01-24'),
    status: 'pending',
  },
  {
    id: '3',
    directoryName: 'Capterra',
    url: 'https://capterra.com',
    confidenceScore: 0.62,
    detectedDate: new Date('2024-01-25'),
    status: 'accepted',
  },
];

// Mock data for blog contacts
export const mockBlogContacts: BlogContact[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah@techblog.com',
    blogUrl: 'https://techblog.com',
    domainAuthority: 78,
    status: 'responded',
    lastContactDate: new Date('2024-01-20'),
    notes: 'Interested in guest post collaboration',
  },
  {
    id: '2',
    name: 'Mike Chen',
    email: 'mike@startupinsights.io',
    blogUrl: 'https://startupinsights.io',
    domainAuthority: 82,
    status: 'contacted',
    lastContactDate: new Date('2024-01-22'),
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily@devnews.com',
    blogUrl: 'https://devnews.com',
    domainAuthority: 85,
    status: 'new',
  },
  {
    id: '4',
    name: 'David Park',
    email: 'david@saasnews.net',
    blogUrl: 'https://saasnews.net',
    domainAuthority: 76,
    status: 'declined',
    lastContactDate: new Date('2024-01-15'),
    notes: 'Not accepting guest posts currently',
  },
];

// Mock data for outreach templates
export const mockOutreachTemplates: OutreachTemplate[] = [
  {
    id: '1',
    name: 'Initial Outreach',
    subject: 'Guest Post Opportunity for {{blog_name}}',
    body: 'Hi {{contact_name}},\n\nI hope this email finds you well. I\'ve been following {{blog_name}} and really appreciate your content on {{topic}}.\n\nI\'d love to contribute a guest post...',
    category: 'Guest Post',
  },
  {
    id: '2',
    name: 'Follow-up',
    subject: 'Following up on guest post opportunity',
    body: 'Hi {{contact_name}},\n\nI wanted to follow up on my previous email about contributing to {{blog_name}}...',
    category: 'Follow-up',
  },
  {
    id: '3',
    name: 'Product Feature Request',
    subject: 'Feature opportunity: {{product_name}}',
    body: 'Hi {{contact_name}},\n\nI noticed you recently covered {{related_topic}} on {{blog_name}}. I thought you might be interested in {{product_name}}...',
    category: 'Product Feature',
  },
];

export const mockAiSummary: AiGenerationSummary = {
  totalDirectories: mockDirectorySubmissions.length,
  uniqueDescriptions: mockDirectorySubmissions.filter((submission) => submission.aiStatus === 'generated').length,
  averageTokens: 365,
  lastRun: new Date('2024-01-26T10:30:00Z'),
  model: 'claude-3-opus',
};
